F1={'L1' : ' Try to have as','L2' : 'good a life as','L3' : 'you can under','L4' : 'the','L5' : 'circumstances.'}
F2={'L1' : ' You have no','L2' : 'real enemies.','L3' : '','L4' : '','L5' : ''}
F3={'L1' : ' Dont tell any','L2' : 'big lies today.','L3' : 'Small ones can','L4' : 'be just as','L5' : 'effective.'}
F4={'L1' : ' Blow it out','L2' : 'your ear.','L3' : '','L4' : '','L5' : ''}
F5={'L1' : ' You would if','L2' : 'you could but','L3' : 'you cant so you','L4' : 'wont.','L5' : ''}
F6={'L1' : ' question = ( to','L2' : ') ? be : ! be;','L3' : '-- Wm.','L4' : 'Shakespeare','L5' : ''}
F7={'L1' : ' Are you making','L2' : 'all this up as','L3' : 'you go along?','L4' : '','L5' : ''}
F8={'L1' : ' You plan things','L2' : 'that you do not','L3' : 'even attempt','L4' : 'because of your','L5' : 'extreme caution.'}
F9={'L1' : ' Perfect day for','L2' : 'scrubbing the','L3' : 'floor and other','L4' : 'exciting things.','L5' : ''}
F10={'L1' : ' You will forget','L2' : 'that you ever','L3' : 'knew me.','L4' : '','L5' : ''}
F11={'L1' : ' Q: How do you','L2' : 'save a drowning','L3' : 'lawyer? A: Throw','L4' : 'him a rock.','L5' : ''}
F12={'L1' : ' You will be','L2' : 'surrounded by','L3' : 'luxury.','L4' : '','L5' : ''}
F13={'L1' : ' Conscience doth','L2' : 'make cowards of','L3' : 'us all. --','L4' : 'Shakespeare','L5' : ''}
F14={'L1' : ' Keep','L2' : 'emotionally','L3' : 'active. Cater to','L4' : 'your favorite','L5' : 'neurosis.'}
F15={'L1' : ' Your supervisor','L2' : 'is thinking','L3' : 'about you.','L4' : '','L5' : ''}
F16={'L1' : ' Advancement in','L2' : 'position.','L3' : '','L4' : '','L5' : ''}
F17={'L1' : ' It was all so','L2' : 'different before','L3' : 'everything','L4' : 'changed.','L5' : ''}
F18={'L1' : ' You will have','L2' : 'domestic','L3' : 'happiness and','L4' : 'faithful','L5' : 'friends.'}
F19={'L1' : ' You need more','L2' : 'time; and you','L3' : 'probably always','L4' : 'will.','L5' : ''}
F20={'L1' : ' Best of all is','L2' : 'never to have','L3' : 'been born.','L4' : 'Second best is','L5' : 'to die soon.'}
F21={'L1' : ' Q: Why was','L2' : 'Stonehenge','L3' : 'abandoned? A: It','L4' : 'wasnt IBM','L5' : 'compatible.'}
F22={'L1' : ' You will','L2' : 'experience a','L3' : 'strong urge to','L4' : 'do good; but it','L5' : 'will pass.'}
F23={'L1' : ' There was a','L2' : 'phone call for','L3' : 'you.','L4' : '','L5' : ''}
F24={'L1' : ' Tomorrow, you','L2' : 'can be anywhere.','L3' : '','L4' : '','L5' : ''}
F25={'L1' : ' Your reasoning','L2' : 'powers are good,','L3' : 'and you are a','L4' : 'fairly good','L5' : 'planner.'}
F26={'L1' : ' Write yourself','L2' : 'a threatening','L3' : 'letter and pen a','L4' : 'defiant reply.','L5' : ''}
F27={'L1' : ' Beware the one','L2' : 'behind you.','L3' : '','L4' : '','L5' : ''}
F28={'L1' : ' Q: Why do WASPs','L2' : 'play golf ? A:','L3' : 'So they can','L4' : 'dress like','L5' : 'pimps.'}
F29={'L1' : ' So youre','L2' : 'back... about','L3' : 'time...','L4' : '','L5' : ''}
F30={'L1' : ' You will soon','L2' : 'meet a person','L3' : 'who will play an','L4' : 'important role','L5' : 'in your life.'}
F31={'L1' : ' You too can','L2' : 'wear a nose','L3' : 'mitten.','L4' : '','L5' : ''}
F32={'L1' : ' You will have a','L2' : 'long and boring','L3' : 'life.','L4' : '','L5' : ''}
F33={'L1' : ' Its all in the','L2' : 'mind, ya know.','L3' : '','L4' : '','L5' : ''}
F34={'L1' : ' You definitely','L2' : 'intend to start','L3' : 'living sometime','L4' : 'soon.','L5' : ''}
F35={'L1' : ' You own a dog,','L2' : 'but you can only','L3' : 'feed a cat.','L4' : '','L5' : ''}
F36={'L1' : ' Is that really','L2' : 'YOU that is','L3' : 'reading this?','L4' : '','L5' : ''}
F37={'L1' : ' Of course you','L2' : 'have a purpose','L3' : '-- to find a','L4' : 'purpose.','L5' : ''}
F38={'L1' : ' Q: Who cuts the','L2' : 'grass on Waltons','L3' : 'Mountain? A:','L4' : 'Lawn Boy.','L5' : ''}
F39={'L1' : ' The whole world','L2' : 'is a tuxedo and','L3' : 'you are a pair','L4' : 'of brown shoes.','L5' : '-- George Gobel'}
F40={'L1' : ' Never laugh at','L2' : 'live dragons. --','L3' : 'Bilbo Baggins','L4' : '[J.R.R. Tolkien,','L5' : 'The Hobbit]'}
F41={'L1' : ' Too much is','L2' : 'just enough. --','L3' : 'Mark Twain, on','L4' : 'whiskey','L5' : ''}
F42={'L1' : ' You have a','L2' : 'strong appeal','L3' : 'for members of','L4' : 'the opposite','L5' : 'sex.'}
F43={'L1' : ' You will give','L2' : 'someone a piece','L3' : 'of your mind,','L4' : 'which you can','L5' : 'ill afford.'}
F44={'L1' : ' Executive','L2' : 'ability is','L3' : 'prominent in','L4' : 'your make-up.','L5' : ''}
F45={'L1' : ' Youre working','L2' : 'under a slight','L3' : 'handicap. You','L4' : 'happen to be','L5' : 'human.'}
F46={'L1' : ' Someone is','L2' : 'speaking well of','L3' : 'you. How','L4' : 'unusual!','L5' : ''}
F47={'L1' : ' If you can read','L2' : 'this, youre too','L3' : 'close.','L4' : '','L5' : ''}
F48={'L1' : ' You will engage','L2' : 'in a profitable','L3' : 'business','L4' : 'activity.','L5' : ''}
F49={'L1' : ' Day of inquiry.','L2' : 'You will be','L3' : 'subpoenaed.','L4' : '','L5' : ''}
F50={'L1' : ' Your domestic','L2' : 'life may be','L3' : 'harmonious.','L4' : '','L5' : ''}
F51={'L1' : ' You are a fluke','L2' : 'of the universe;','L3' : 'you have no','L4' : 'right to be','L5' : 'here.'}
F52={'L1' : ' Its lucky youre','L2' : 'going so slowly,','L3' : 'because youre','L4' : 'going in the','L5' : 'wrong direction.'}
F53={'L1' : ' Q: What do you','L2' : 'call a boomerang','L3' : 'that doesnt come','L4' : 'back? A: A','L5' : 'stick.'}
F54={'L1' : ' If you laid all','L2' : 'of our laws end','L3' : 'to end, there','L4' : 'would be no end.','L5' : '-- Mark Twain'}
F55={'L1' : ' You will','L2' : 'remember','L3' : 'something that','L4' : 'you should not','L5' : 'have forgotten.'}
F56={'L1' : ' You recoil from','L2' : 'the crude; you','L3' : 'tend naturally','L4' : 'toward the','L5' : 'exquisite.'}
F57={'L1' : ' Stay the curse.','L2' : '','L3' : '','L4' : '','L5' : ''}
F58={'L1' : ' Youve been','L2' : 'leading a dogs','L3' : 'life. Stay off','L4' : 'the furniture.','L5' : ''}
F59={'L1' : ' Keep it short','L2' : 'for pithy sake.','L3' : '','L4' : '','L5' : ''}
F60={'L1' : ' Increased','L2' : 'knowledge will','L3' : 'help you now.','L4' : 'Have mates phone','L5' : 'bugged.'}
F61={'L1' : ' A day for firm','L2' : 'decisions!!!!!','L3' : 'Or is it?','L4' : '','L5' : ''}
F62={'L1' : ' Everything will','L2' : 'be just','L3' : 'tickety-boo','L4' : 'today.','L5' : ''}
F63={'L1' : ' You will be a','L2' : 'winner today.','L3' : 'Pick a fight','L4' : 'with a','L5' : 'four-year-old.'}
F64={'L1' : ' Future looks','L2' : 'spotty. You will','L3' : 'spill soup in','L4' : 'late evening.','L5' : ''}
F65={'L1' : ' Break into jail','L2' : 'and claim police','L3' : 'brutality.','L4' : '','L5' : ''}
F66={'L1' : ' You never know','L2' : 'how many friends','L3' : 'you have until','L4' : 'you rent a house','L5' : 'on the beach.'}
F67={'L1' : ' Dont look now,','L2' : 'but there is a','L3' : 'multi-legged','L4' : 'creature on your','L5' : 'shoulder.'}
F68={'L1' : ' You have','L2' : 'Egyptian flu:','L3' : 'youre going to','L4' : 'be a mummy.','L5' : ''}
F69={'L1' : ' Do something','L2' : 'unusual today.','L3' : 'Pay a bill.','L4' : '','L5' : ''}
F70={'L1' : ' Chicken Little','L2' : 'was right.','L3' : '','L4' : '','L5' : ''}
F71={'L1' : ' Go to a movie','L2' : 'tonight.','L3' : 'Darkness becomes','L4' : 'you.','L5' : ''}
F72={'L1' : ' Your boyfriend','L2' : 'takes chocolate','L3' : 'from strangers.','L4' : '','L5' : ''}
F73={'L1' : ' You are not','L2' : 'dead yet. But','L3' : 'watch for','L4' : 'further reports.','L5' : ''}
F74={'L1' : ' You are going','L2' : 'to have a new','L3' : 'love affair.','L4' : '','L5' : ''}
F75={'L1' : ' Communicate! It','L2' : 'cant make things','L3' : 'any worse.','L4' : '','L5' : ''}
F76={'L1' : ' You will be','L2' : 'awarded the','L3' : 'Nobel Peace','L4' : 'Prize...','L5' : 'posthumously.'}
F77={'L1' : ' You shall be','L2' : 'rewarded for a','L3' : 'dastardly deed.','L4' : '','L5' : ''}
F78={'L1' : ' You should go','L2' : 'home.','L3' : '','L4' : '','L5' : ''}
F79={'L1' : ' Good news. Ten','L2' : 'weeks from','L3' : 'Friday will be a','L4' : 'pretty good day.','L5' : ''}
F80={'L1' : ' You possess a','L2' : 'mind not merely','L3' : 'twisted, but','L4' : 'actually','L5' : 'sprained.'}
F81={'L1' : ' You will','L2' : 'contract a rare','L3' : 'disease.','L4' : '','L5' : ''}
F82={'L1' : ' In the stairway','L2' : 'of life, youd','L3' : 'best take the','L4' : 'elevator.','L5' : ''}
F83={'L1' : ' You are','L2' : 'standing on my','L3' : 'toes.','L4' : '','L5' : ''}
F84={'L1' : ' Q: Do you know','L2' : 'what the death','L3' : 'rate around here','L4' : 'is? A: One per','L5' : 'person.'}
F85={'L1' : ' The Public is','L2' : 'merely a','L3' : 'multiplied me.','L4' : '-- Mark Twain','L5' : ''}
F86={'L1' : ' Q: Whats hard','L2' : 'going in and','L3' : 'soft and sticky','L4' : 'coming out? A:','L5' : 'Chewing gum.'}
F87={'L1' : ' Afternoon very','L2' : 'favorable for','L3' : 'romance. Try a','L4' : 'single person','L5' : 'for a change.'}
F88={'L1' : ' Learn to pause','L2' : '-- or nothing','L3' : 'worthwhile can','L4' : 'catch up to you.','L5' : ''}
F89={'L1' : ' Do nothing','L2' : 'unless you must,','L3' : 'and when you','L4' : 'must act --','L5' : 'hesitate.'}
F90={'L1' : ' Every why hath','L2' : 'a wherefore. --','L3' : 'William','L4' : 'Shakespeare, A','L5' : 'Comedy of Errors'}
F91={'L1' : ' Caution:','L2' : 'breathing may be','L3' : 'hazardous to','L4' : 'your health.','L5' : ''}
F92={'L1' : ' You will be','L2' : 'married within a','L3' : 'year, and','L4' : 'divorced within','L5' : 'two.'}
F93={'L1' : ' You get along','L2' : 'very well with','L3' : 'everyone except','L4' : 'animals and','L5' : 'people.'}
F94={'L1' : ' Your present','L2' : 'plans will be','L3' : 'successful.','L4' : '','L5' : ''}
F95={'L1' : ' Dont kiss an','L2' : 'elephant on the','L3' : 'lips today.','L4' : '','L5' : ''}
F96={'L1' : ' Expect the','L2' : 'worst, its the','L3' : 'least you can','L4' : 'do.','L5' : ''}
F97={'L1' : ' Today is the','L2' : 'last day of your','L3' : 'life so far.','L4' : '','L5' : ''}
F98={'L1' : ' You will gain','L2' : 'money by an','L3' : 'immoral action.','L4' : '','L5' : ''}
F99={'L1' : ' Stay away from','L2' : 'hurricanes for a','L3' : 'while.','L4' : '','L5' : ''}
F100={'L1' : ' You are a very','L2' : 'redundant','L3' : 'person, thats','L4' : 'what kind of','L5' : 'person you are.'}
F101={'L1' : ' When one burns','L2' : 'ones bridges,','L3' : 'what a very nice','L4' : 'fire it makes.','L5' : '-- Dylan Thomas'}
F102={'L1' : ' Big book, big','L2' : 'bore. --','L3' : 'Callimachus','L4' : '','L5' : ''}
F103={'L1' : ' Alimony and','L2' : 'bribes will','L3' : 'engage a large','L4' : 'share of your','L5' : 'wealth.'}
F104={'L1' : ' Snow Day --','L2' : 'stay home.','L3' : '','L4' : '','L5' : ''}
F105={'L1' : ' Q: What is the','L2' : 'sound of one cat','L3' : 'napping? A: Mu.','L4' : '','L5' : ''}
F106={'L1' : ' Look afar and','L2' : 'see the end from','L3' : 'the beginning.','L4' : '','L5' : ''}
F107={'L1' : ' Talkers are no','L2' : 'good doers. --','L3' : 'William','L4' : 'Shakespeare,','L5' : 'Henry VI'}
F108={'L1' : ' A few hours','L2' : 'grace before the','L3' : 'madness begins','L4' : 'again.','L5' : ''}
F109={'L1' : ' You will feel','L2' : 'hungry again in','L3' : 'another hour.','L4' : '','L5' : ''}
F110={'L1' : ' You will be','L2' : 'married within a','L3' : 'year.','L4' : '','L5' : ''}
F111={'L1' : ' Your lover will','L2' : 'never wish to','L3' : 'leave you.','L4' : '','L5' : ''}
F112={'L1' : ' Your depth of','L2' : 'comprehension','L3' : 'may tend to make','L4' : 'you lax in','L5' : 'worldly ways.'}
F113={'L1' : ' Q: Whats tan','L2' : 'and black and','L3' : 'looks great on a','L4' : 'lawyer? A: A','L5' : 'doberman.'}
F114={'L1' : ' Give him an','L2' : 'evasive answer.','L3' : '','L4' : '','L5' : ''}
F115={'L1' : ' You fill a','L2' : 'much-needed gap.','L3' : '','L4' : '','L5' : ''}
F116={'L1' : ' You will gain','L2' : 'money by an','L3' : 'illegal action.','L4' : '','L5' : ''}
F117={'L1' : ' You will visit','L2' : 'the Dung Pits of','L3' : 'Glive soon.','L4' : '','L5' : ''}
F118={'L1' : ' You will not be','L2' : 'elected to','L3' : 'public office','L4' : 'this year.','L5' : ''}
F119={'L1' : ' Good day for','L2' : 'overcoming','L3' : 'obstacles. Try a','L4' : 'steeplechase.','L5' : ''}
F120={'L1' : ' Today is what','L2' : 'happened to','L3' : 'yesterday.','L4' : '','L5' : ''}
F121={'L1' : ' Water, taken in','L2' : 'moderation','L3' : 'cannot hurt','L4' : 'anybody. -- Mark','L5' : 'Twain'}
F122={'L1' : ' You will be','L2' : 'reincarnated as','L3' : 'a toad; and you','L4' : 'will be much','L5' : 'happier.'}
F123={'L1' : ' You like to','L2' : 'form new','L3' : 'friendships and','L4' : 'make new','L5' : 'acquaintances.'}
F124={'L1' : ' Harp not on','L2' : 'that string. --','L3' : 'William','L4' : 'Shakespeare,','L5' : 'Henry VI'}
F125={'L1' : ' Familiarity','L2' : 'breeds contempt','L3' : '-- and children.','L4' : '-- Mark Twain','L5' : ''}
F126={'L1' : ' You dialed','L2' : '5483.','L3' : '','L4' : '','L5' : ''}
F127={'L1' : ' What I tell you','L2' : 'three times is','L3' : 'true. -- Lewis','L4' : 'Carroll','L5' : ''}
F128={'L1' : ' You will','L2' : 'inherit millions','L3' : 'of dollars.','L4' : '','L5' : ''}
F129={'L1' : ' Never look up','L2' : 'when dragons fly','L3' : 'overhead.','L4' : '','L5' : ''}
F130={'L1' : ' You will never','L2' : 'know hunger.','L3' : '','L4' : '','L5' : ''}
F131={'L1' : ' You will have','L2' : 'good luck and','L3' : 'overcome many','L4' : 'hardships.','L5' : ''}
F132={'L1' : ' Man is the only','L2' : 'animal that','L3' : 'blushes -- or','L4' : 'needs to. --','L5' : 'Mark Twain'}
F133={'L1' : ' Never reveal','L2' : 'your best','L3' : 'argument.','L4' : '','L5' : ''}
F134={'L1' : ' Dont let your','L2' : 'mind wander --','L3' : 'its too little','L4' : 'to be let out','L5' : 'alone.'}
F135={'L1' : ' There is a fly','L2' : 'on your nose.','L3' : '','L4' : '','L5' : ''}
F136={'L1' : ' Your love life','L2' : 'will be...','L3' : 'interesting.','L4' : '','L5' : ''}
F137={'L1' : ' Do what comes','L2' : 'naturally.','L3' : 'Seethe and fume','L4' : 'and throw a','L5' : 'tantrum.'}
F138={'L1' : ' Dont get stuck','L2' : 'in a closet --','L3' : 'wear yourself','L4' : 'out.','L5' : ''}
F139={'L1' : ' Artistic','L2' : 'ventures','L3' : 'highlighted. Rob','L4' : 'a museum.','L5' : ''}
F140={'L1' : ' Wrinkles should','L2' : 'merely indicate','L3' : 'where smiles','L4' : 'have been. --','L5' : 'Mark Twain'}
F141={'L1' : ' Tempt not a','L2' : 'desperate man.','L3' : '-- William','L4' : 'Shakespeare,','L5' : 'Romeo and Juliet'}
F142={'L1' : ' You will be run','L2' : 'over by a beer','L3' : 'truck.','L4' : '','L5' : ''}
F143={'L1' : ' You are','L2' : 'magnetic in your','L3' : 'bearing.','L4' : '','L5' : ''}
F144={'L1' : ' Dont you feel','L2' : 'more like you do','L3' : 'now than you did','L4' : 'when you came','L5' : 'in?'}
F145={'L1' : ' You tread upon','L2' : 'my patience. --','L3' : 'William','L4' : 'Shakespeare,','L5' : 'Henry IV'}
F146={'L1' : ' You are','L2' : 'confused; but','L3' : 'this is your','L4' : 'normal state.','L5' : ''}
F147={'L1' : ' Another good','L2' : 'night not to','L3' : 'sleep in a','L4' : 'eucalyptus tree.','L5' : ''}
F148={'L1' : ' Ships are safe','L2' : 'in harbor, but','L3' : 'they were never','L4' : 'meant to stay','L5' : 'there.'}
F149={'L1' : ' Save energy: be','L2' : 'apathetic.','L3' : '','L4' : '','L5' : ''}
F150={'L1' : ' He is now','L2' : 'rising from','L3' : 'affluence to','L4' : 'poverty. -- Mark','L5' : 'Twain'}
