F1={'L1' : ' You will','L2' : 'overcome your','L3' : 'inhibitions.','L4' : '','L5' : ''}
F2={'L1' : ' You will','L2' : 'prosper in the','L3' : 'field of','L4' : 'entertainment.','L5' : ''}
F3={'L1' : ' You will see','L2' : 'success ahead;','L3' : 'more money is in','L4' : 'prospect.','L5' : ''}
F4={'L1' : ' You will shine','L2' : 'at some civic','L3' : 'function.','L4' : '','L5' : ''}
F5={'L1' : ' You will soon','L2' : 'be blessed with','L3' : 'unexpected good','L4' : 'luck.','L5' : ''}
F6={'L1' : ' You will soon','L2' : 'be confronted','L3' : 'with limitless','L4' : 'opportunities.','L5' : ''}
F7={'L1' : ' You will soon','L2' : 'be honoured by','L3' : 'someone you','L4' : 'respect.','L5' : ''}
F8={'L1' : ' You will soon','L2' : 'be in the','L3' : 'limelight.','L4' : '','L5' : ''}
F9={'L1' : ' You will soon','L2' : 'be very proud of','L3' : 'someone close to','L4' : 'you.','L5' : ''}
F10={'L1' : ' You will soon','L2' : 'experience great','L3' : 'happiness.','L4' : '','L5' : ''}
F11={'L1' : ' You will soon','L2' : 'face something','L3' : 'new and','L4' : 'exciting.','L5' : ''}
F12={'L1' : ' You will soon','L2' : 'find something','L3' : 'lost long ago.','L4' : '','L5' : ''}
F13={'L1' : ' You will soon','L2' : 'receive an','L3' : 'invitation to a','L4' : 'sporting event.','L5' : ''}
F14={'L1' : ' You will soon','L2' : 'receive very','L3' : 'special','L4' : 'attention.','L5' : ''}
F15={'L1' : ' You will take a','L2' : 'chance in','L3' : 'something in the','L4' : 'near future.','L5' : ''}
F16={'L1' : ' You will take a','L2' : 'chance in the','L3' : 'near future and','L4' : 'win.','L5' : ''}
F17={'L1' : ' You will touch','L2' : 'the hearts of','L3' : 'many with your','L4' : 'gift.','L5' : ''}
F18={'L1' : ' You will travel','L2' : 'far and wide for','L3' : 'both business','L4' : 'and pleasure.','L5' : ''}
F19={'L1' : ' You will try','L2' : 'something new.','L3' : '','L4' : '','L5' : ''}
F20={'L1' : ' You will win','L2' : 'favours when you','L3' : 'expand your','L4' : 'social circle.','L5' : ''}
F21={'L1' : ' You will','L2' : 'witness a','L3' : 'special','L4' : 'ceremony.','L5' : ''}
F22={'L1' : ' You would be','L2' : 'wise not to seek','L3' : 'too much from','L4' : 'others at this','L5' : 'time.'}
F23={'L1' : ' You would be','L2' : 'wise to postpone','L3' : 'changes until','L4' : 'next month.','L5' : ''}
F24={'L1' : ' Your ability to','L2' : 'listen makes you','L3' : 'wise.','L4' : '','L5' : ''}
F25={'L1' : ' Your ability to','L2' : 'love will help a','L3' : 'child in need.','L4' : '','L5' : ''}
F26={'L1' : ' Your ability to','L2' : 'share will help','L3' : 'someone in need.','L4' : '','L5' : ''}
F27={'L1' : ' Your anxieties','L2' : 'are beginning to','L3' : 'clear.','L4' : '','L5' : ''}
F28={'L1' : ' Your','L2' : 'appreciation of','L3' : 'the arts will','L4' : 'bring new','L5' : 'opportunities.'}
F29={'L1' : ' Your belief in','L2' : 'the goodness of','L3' : 'mankind will be','L4' : 'rewarded.','L5' : ''}
F30={'L1' : ' Your biggest','L2' : 'problem will','L3' : 'soon be solved.','L4' : '','L5' : ''}
F31={'L1' : ' Your charm and','L2' : 'courtesy will be','L3' : 'advantageous to','L4' : 'your goal.','L5' : ''}
F32={'L1' : ' Your command of','L2' : 'the language','L3' : 'will open doors','L4' : 'for you.','L5' : ''}
F33={'L1' : ' Your concept of','L2' : 'handling funds','L3' : 'requires review.','L4' : '','L5' : ''}
F34={'L1' : ' Your dearest','L2' : 'wish will come','L3' : 'true.','L4' : '','L5' : ''}
F35={'L1' : ' Your deepest','L2' : 'desires will be','L3' : 'granted.','L4' : '','L5' : ''}
F36={'L1' : ' Your','L2' : 'dream-maker is','L3' : 'making your','L4' : 'ideals real.','L5' : ''}
F37={'L1' : ' Your efforts','L2' : 'will be well','L3' : 'rewarded. Be','L4' : 'patient.','L5' : ''}
F38={'L1' : ' Your efforts','L2' : 'will pay off.','L3' : '','L4' : '','L5' : ''}
F39={'L1' : ' Your empathy','L2' : 'will help','L3' : 'someone out of a','L4' : 'difficult','L5' : 'situation.'}
F40={'L1' : ' Your experience','L2' : 'will help a','L3' : 'friend make it','L4' : 'to the top.','L5' : ''}
F41={'L1' : ' Your','L2' : 'expressiveness','L3' : 'will bring new','L4' : 'opportunities.','L5' : ''}
F42={'L1' : ' Your fantasy','L2' : 'will come true.','L3' : '','L4' : '','L5' : ''}
F43={'L1' : ' Your financial','L2' : 'outlook is','L3' : 'excellent.','L4' : '','L5' : ''}
F44={'L1' : ' Your friends','L2' : 'will be generous','L3' : 'with','L4' : 'invitations.','L5' : ''}
F45={'L1' : ' Your future is','L2' : 'as boundless as','L3' : 'the lofty','L4' : 'heaven.','L5' : ''}
F46={'L1' : ' Your future','L2' : 'looks very','L3' : 'promising.','L4' : '','L5' : ''}
F47={'L1' : ' Your future','L2' : 'will be happy','L3' : 'and productive.','L4' : '','L5' : ''}
F48={'L1' : ' Your genuine','L2' : 'talent will find','L3' : 'its way to','L4' : 'success.','L5' : ''}
F49={'L1' : ' Your good','L2' : 'listening skills','L3' : 'will open many','L4' : 'doors to you.','L5' : ''}
F50={'L1' : ' Your good','L2' : 'nature will','L3' : 'bring you','L4' : 'unbounded','L5' : 'happiness.'}
F51={'L1' : ' Your hard work','L2' : 'will soon show','L3' : 'results.','L4' : '','L5' : ''}
F52={'L1' : ' Your home is a','L2' : 'pleasant place','L3' : 'from which you','L4' : 'draw happiness.','L5' : ''}
F53={'L1' : ' Your honesty','L2' : 'will be','L3' : 'recognized.','L4' : '','L5' : ''}
F54={'L1' : ' Your job needs','L2' : 'more','L3' : 'concentration.','L4' : 'Success will be','L5' : 'achieved.'}
F55={'L1' : ' Your keen sense','L2' : 'of humour will','L3' : 'make you many','L4' : 'good friends.','L5' : ''}
F56={'L1' : ' Your kindness','L2' : 'to others shall','L3' : 'be returned to','L4' : 'you threefold.','L5' : ''}
F57={'L1' : ' Your kindness','L2' : 'will lead you to','L3' : 'success.','L4' : '','L5' : ''}
F58={'L1' : ' Your labours','L2' : 'will bear sweet','L3' : 'fruit.','L4' : '','L5' : ''}
F59={'L1' : ' Your life will','L2' : 'be filled with','L3' : 'sunshine.','L4' : '','L5' : ''}
F60={'L1' : ' Your life will','L2' : 'be full of true','L3' : 'friendships.','L4' : '','L5' : ''}
F61={'L1' : ' Your life will','L2' : 'be happy and','L3' : 'peaceful.','L4' : '','L5' : ''}
F62={'L1' : ' Your love of','L2' : 'peace will','L3' : 'affect the','L4' : 'course of','L5' : 'events.'}
F63={'L1' : ' Your love of','L2' : 'sports will','L3' : 'bring a change','L4' : 'in your life.','L5' : ''}
F64={'L1' : ' Your loyalties','L2' : 'are clear when','L3' : 'it comes to','L4' : 'friends.','L5' : ''}
F65={'L1' : ' Your loyalty','L2' : 'shall be','L3' : 'rewarded.','L4' : '','L5' : ''}
F66={'L1' : ' Your luck will','L2' : 'be good today.','L3' : '','L4' : '','L5' : ''}
F67={'L1' : ' Your luck will','L2' : 'soon be at a','L3' : 'high.','L4' : '','L5' : ''}
F68={'L1' : ' Your magnetic','L2' : 'personality will','L3' : 'draw people to','L4' : 'you.','L5' : ''}
F69={'L1' : ' Your mastery of','L2' : 'every situation','L3' : 'will soon prove','L4' : 'very important.','L5' : ''}
F70={'L1' : ' Your mind,','L2' : 'being creative','L3' : 'and original,','L4' : 'will make you','L5' : 'famous.'}
F71={'L1' : ' Your most','L2' : 'difficult','L3' : 'problems will','L4' : 'soon be nothing.','L5' : ''}
F72={'L1' : ' Your next','L2' : 'important','L3' : 'purchase will be','L4' : 'a bargain.','L5' : ''}
F73={'L1' : ' Your','L2' : 'originality will','L3' : 'be rewarded.','L4' : '','L5' : ''}
F74={'L1' : ' Your partner','L2' : 'will be proud of','L3' : 'you.','L4' : '','L5' : ''}
F75={'L1' : ' Your path is','L2' : 'difficult, but','L3' : 'will be amply','L4' : 'rewarded.','L5' : ''}
F76={'L1' : ' Your reputation','L2' : 'for being honest','L3' : 'will bring','L4' : 'rewards.','L5' : ''}
F77={'L1' : ' Your search for','L2' : 'knowledge will','L3' : 'lead you to high','L4' : 'places.','L5' : ''}
F78={'L1' : ' Your secret','L2' : 'venture will','L3' : 'work out','L4' : 'brilliantly.','L5' : ''}
F79={'L1' : ' Your','L2' : 'self-confidence','L3' : 'is warranted.','L4' : '','L5' : ''}
F80={'L1' : ' Your','L2' : 'self-reliance','L3' : 'will solve most','L4' : 'of your own','L5' : 'problems.'}
F81={'L1' : ' Your','L2' : 'self-restraint','L3' : 'will pay','L4' : 'dividends.','L5' : ''}
F82={'L1' : ' Your senior','L2' : 'years will be','L3' : 'happy &','L4' : 'successful.','L5' : ''}
F83={'L1' : ' Your sense of','L2' : 'humour will','L3' : 'ensure your','L4' : 'success.','L5' : ''}
F84={'L1' : ' Your sense of','L2' : 'humour will be','L3' : 'your key to','L4' : 'success.','L5' : ''}
F85={'L1' : ' Your silence at','L2' : 'this time is','L3' : 'important.','L4' : '','L5' : ''}
F86={'L1' : ' Your social','L2' : 'life could be','L3' : 'very glamorous','L4' : 'and rewarding','L5' : 'now.'}
F87={'L1' : ' Your strong','L2' : 'principles will','L3' : 'lead you to','L4' : 'happiness.','L5' : ''}
F88={'L1' : ' Your talents','L2' : 'are in fine','L3' : 'shape; utilize','L4' : 'them to their','L5' : 'fullest.'}
F89={'L1' : ' Your talents','L2' : 'will be','L3' : 'recognized and','L4' : 'suitably','L5' : 'rewarded.'}
F90={'L1' : ' Your talent','L2' : 'will bring joy','L3' : 'to many people.','L4' : '','L5' : ''}
F91={'L1' : ' Your talents','L2' : 'will soon be','L3' : 'recognized.','L4' : '','L5' : ''}
F92={'L1' : ' Your','L2' : 'understanding','L3' : 'will help a','L4' : 'friend in need.','L5' : ''}
F93={'L1' : ' Your venture','L2' : 'will be a','L3' : 'success.','L4' : '','L5' : ''}
F94={'L1' : ' Your wisdom','L2' : 'shall bring you','L3' : 'much respect in','L4' : 'later years.','L5' : ''}
F95={'L1' : ' Your wit will','L2' : 'lead you into a','L3' : 'very interesting','L4' : 'situation.','L5' : ''}
F96={'L1' : ' Your worries','L2' : 'shall soon be','L3' : 'dispelled.','L4' : '','L5' : ''}
F97={'L1' : ' He who throws','L2' : 'dirt is losing','L3' : 'ground.','L4' : '','L5' : ''}
F98={'L1' : ' A woman who','L2' : 'seeks to be','L3' : 'equal with men','L4' : 'lacks ambition.','L5' : 'Ouch!!!'}
F99={'L1' : ' The greatest','L2' : 'danger could be','L3' : 'your stupidity.','L4' : '','L5' : ''}
F100={'L1' : ' He who laughs','L2' : 'last is laughing','L3' : 'at you.','L4' : '','L5' : ''}
F101={'L1' : ' A closed mouth','L2' : 'gathers no feet.','L3' : '','L4' : '','L5' : ''}
F102={'L1' : ' A conclusion is','L2' : 'simply the place','L3' : 'where you got','L4' : 'tired of','L5' : 'thinking.'}
F103={'L1' : ' A cynic is only','L2' : 'a frustrated','L3' : 'optimist.','L4' : '','L5' : ''}
F104={'L1' : ' A fanatic is','L2' : 'one who cant','L3' : 'change his mind,','L4' : 'and wont change','L5' : 'the subject.'}
F105={'L1' : ' The world may','L2' : 'be your oyster,','L3' : 'but it doesnt','L4' : 'mean youll get','L5' : 'its pearl.'}
F106={'L1' : ' Flattery will','L2' : 'go far tonight.','L3' : '','L4' : '','L5' : ''}
F107={'L1' : ' Our first and','L2' : 'last love...is','L3' : 'self love.','L4' : '','L5' : ''}
F108={'L1' : ' You were born','L2' : 'with the skill','L3' : 'to communicate','L4' : 'with people','L5' : 'easily.'}
F109={'L1' : ' You are','L2' : 'talented in many','L3' : 'ways.','L4' : '','L5' : ''}
F110={'L1' : ' Any rough times','L2' : 'are behind you.','L3' : '','L4' : '','L5' : ''}
F111={'L1' : ' Grand','L2' : 'adventures await','L3' : 'those who are','L4' : 'willing to turn','L5' : 'the corner.'}
F112={'L1' : ' The smart thing','L2' : 'is to prepare','L3' : 'for the','L4' : 'unexpected.','L5' : ''}
F113={'L1' : ' There is yet','L2' : 'time enough for','L3' : 'you to take a','L4' : 'different path.','L5' : ''}
F114={'L1' : ' You are very','L2' : 'expressive and','L3' : 'positive in','L4' : 'words, act and','L5' : 'feeling.'}
F115={'L1' : ' A scholars ink','L2' : 'lasts longer','L3' : 'than a martyrs','L4' : 'blood.','L5' : ''}
F116={'L1' : ' Little and','L2' : 'often makes','L3' : 'much.','L4' : '','L5' : ''}
F117={'L1' : ' The days you','L2' : 'work are the','L3' : 'best days.','L4' : '','L5' : ''}
F118={'L1' : ' The hard times','L2' : 'will begin to','L3' : 'fade, joy will','L4' : 'take their','L5' : 'place.'}
F119={'L1' : ' The first step','L2' : 'to better times','L3' : 'is to imagine','L4' : 'them.','L5' : ''}
F120={'L1' : ' When you speak','L2' : 'honestly and','L3' : 'openly, others','L4' : 'truly listen to','L5' : 'you.'}
F121={'L1' : ' It doesnt','L2' : 'matter. Who is','L3' : 'without a flaw?','L4' : '','L5' : ''}
F122={'L1' : ' It is much','L2' : 'wiser to take','L3' : 'advice than to','L4' : 'give it.','L5' : ''}
F123={'L1' : ' A thrilling','L2' : 'time is in your','L3' : 'immediate','L4' : 'future.','L5' : ''}
F124={'L1' : ' The skills you','L2' : 'have gathered','L3' : 'will one day','L4' : 'come in handy.','L5' : ''}
F125={'L1' : ' Every excess','L2' : 'becomes a vice.','L3' : '','L4' : '','L5' : ''}
F126={'L1' : ' Keep in close','L2' : 'touch with what','L3' : 'your competition','L4' : 'is doing.','L5' : ''}
F127={'L1' : ' You can always','L2' : 'find happiness','L3' : 'at work on','L4' : 'Friday.','L5' : ''}
F128={'L1' : ' The secret of','L2' : 'getting ahead is','L3' : 'getting started.','L4' : '','L5' : ''}
F129={'L1' : ' Do not mistake','L2' : 'temptation for','L3' : 'opportunity.','L4' : '','L5' : ''}
F130={'L1' : ' You will have','L2' : 'gold pieces by','L3' : 'the bushel.','L4' : '','L5' : ''}
F131={'L1' : ' Put the data','L2' : 'you have','L3' : 'uncovered to','L4' : 'beneficial use.','L5' : ''}
F132={'L1' : ' Your past','L2' : 'success will be','L3' : 'overshadowed by','L4' : 'your future','L5' : 'success.'}
F133={'L1' : ' Skill comes','L2' : 'from diligence.','L3' : '','L4' : '','L5' : ''}
F134={'L1' : ' Dont forget to','L2' : 'do good deeds as','L3' : 'you accumulate','L4' : 'wealth.','L5' : ''}
F135={'L1' : ' Avert','L2' : 'misunderstanding','L3' : 'by calm, poise,','L4' : 'and balance.','L5' : ''}
F136={'L1' : ' Consolidate','L2' : 'rather than','L3' : 'expand business','L4' : 'projects in the','L5' : 'near future.'}
F137={'L1' : ' Delay is the','L2' : 'antidote for','L3' : 'anger.','L4' : '','L5' : ''}
F138={'L1' : ' Get ready! Good','L2' : 'fortune comes in','L3' : 'bunches.','L4' : '','L5' : ''}
F139={'L1' : ' None of the','L2' : 'secrets of','L3' : 'success will','L4' : 'work unless you','L5' : 'do.'}
F140={'L1' : ' You will be','L2' : 'wise not to seek','L3' : 'too much from','L4' : 'others.','L5' : ''}
F141={'L1' : ' There is a true','L2' : 'and sincere','L3' : 'friendship','L4' : 'between you and','L5' : 'your friends.'}
F142={'L1' : ' You find beauty','L2' : 'in ordinary','L3' : 'things, do not','L4' : 'lose this','L5' : 'ability.'}
F143={'L1' : ' Your blessing','L2' : 'is no more than','L3' : 'being safe and','L4' : 'sound for the','L5' : 'whole lifetime.'}
F144={'L1' : ' Plan for many','L2' : 'pleasures ahead.','L3' : '','L4' : '','L5' : ''}
F145={'L1' : ' The joyfulness','L2' : 'of a man','L3' : 'prolongeth his','L4' : 'days.','L5' : ''}
F146={'L1' : ' Something you','L2' : 'lost will soon','L3' : 'turn up.','L4' : '','L5' : ''}
F147={'L1' : ' Your heart is','L2' : 'pure, and your','L3' : 'mind clear, and','L4' : 'your soul','L5' : 'devout.'}
F148={'L1' : ' Excitement and','L2' : 'intrigue follow','L3' : 'you closely','L4' : 'wherever you go!','L5' : ''}
F149={'L1' : ' As the purse is','L2' : 'emptied the','L3' : 'heart is filled.','L4' : '','L5' : ''}
F150={'L1' : ' Be mischievous','L2' : 'and you will not','L3' : 'be lonesome.','L4' : '','L5' : ''}
