F1={'L1' : ' Your flair for','L2' : 'the creative','L3' : 'takes an','L4' : 'important place','L5' : 'in your life.'}
F2={'L1' : ' Your artistic','L2' : 'talents win the','L3' : 'approval and','L4' : 'applause of','L5' : 'others.'}
F3={'L1' : ' Your greatest','L2' : 'fortune is the','L3' : 'large number of','L4' : 'friends you','L5' : 'have.'}
F4={'L1' : ' Dont ask, dont','L2' : 'say. Everything','L3' : 'lies in silence.','L4' : '','L5' : ''}
F5={'L1' : ' Be prepared to','L2' : 'accept a','L3' : 'wondrous','L4' : 'opportunity in','L5' : 'the days ahead!'}
F6={'L1' : ' Fame, riches','L2' : 'and romance are','L3' : 'yours for the','L4' : 'asking.','L5' : ''}
F7={'L1' : ' Good things are','L2' : 'being said about','L3' : 'you.','L4' : '','L5' : ''}
F8={'L1' : ' Smiling often','L2' : 'can make you','L3' : 'look and feel','L4' : 'younger.','L5' : ''}
F9={'L1' : ' Someone is','L2' : 'speaking well of','L3' : 'you.','L4' : '','L5' : ''}
F10={'L1' : ' A friend is a','L2' : 'present you give','L3' : 'yourself.','L4' : '','L5' : ''}
F11={'L1' : ' A quiet evening','L2' : 'with friends is','L3' : 'the best tonic','L4' : 'for a long day.','L5' : ''}
F12={'L1' : ' A single kind','L2' : 'word will keep','L3' : 'one warm for','L4' : 'years.','L5' : ''}
F13={'L1' : ' Anger begins','L2' : 'with folly, and','L3' : 'ends with','L4' : 'regret.','L5' : ''}
F14={'L1' : ' Generosity and','L2' : 'perfection are','L3' : 'your everlasting','L4' : 'goals.','L5' : ''}
F15={'L1' : ' Happy news is','L2' : 'on its way to','L3' : 'you.','L4' : '','L5' : ''}
F16={'L1' : ' He who laughs','L2' : 'at himself never','L3' : 'runs out of','L4' : 'things to laugh','L5' : 'at.'}
F17={'L1' : ' Let there be','L2' : 'magic in your','L3' : 'smile and','L4' : 'firmness in your','L5' : 'handshake.'}
F18={'L1' : ' Nature, time','L2' : 'and patience are','L3' : 'the three best','L4' : 'physicians.','L5' : ''}
F19={'L1' : ' Strong and','L2' : 'bitter words','L3' : 'indicate a weak','L4' : 'cause.','L5' : ''}
F20={'L1' : ' You will have a','L2' : 'very pleasant','L3' : 'experience.','L4' : '','L5' : ''}
F21={'L1' : ' You will step','L2' : 'on the soil of','L3' : 'many countries.','L4' : '','L5' : ''}
F22={'L1' : ' Your','L2' : 'everlasting','L3' : 'patience will be','L4' : 'rewarded sooner','L5' : 'or later.'}
F23={'L1' : ' Your great','L2' : 'attention to','L3' : 'detail is both a','L4' : 'blessing and a','L5' : 'curse.'}
F24={'L1' : ' Your ability to','L2' : 'juggle many','L3' : 'tasks will take','L4' : 'you far.','L5' : ''}
F25={'L1' : ' A friend asks','L2' : 'only for your','L3' : 'time, not your','L4' : 'money.','L5' : ''}
F26={'L1' : ' You will be','L2' : 'invited to an','L3' : 'exciting event.','L4' : '','L5' : ''}
F27={'L1' : ' A warm smile is','L2' : 'testimony of a','L3' : 'generous nature.','L4' : '','L5' : ''}
F28={'L1' : ' A secret','L2' : 'admirer will','L3' : 'soon send you a','L4' : 'sign of','L5' : 'affection.'}
F29={'L1' : ' Love asks me no','L2' : 'questions, and','L3' : 'gives me endless','L4' : 'support.','L5' : '--Shakespeare'}
F30={'L1' : ' Love is for the','L2' : 'lucky and the','L3' : 'brave.','L4' : '','L5' : ''}
F31={'L1' : ' If you','L2' : 'continually','L3' : 'give, you will','L4' : 'continually','L5' : 'have.'}
F32={'L1' : ' If you want the','L2' : 'rainbow, you','L3' : 'must put up with','L4' : 'the rain.','L5' : '--Dolly Parton'}
F33={'L1' : ' If you would be','L2' : 'loved, love and','L3' : 'be lovable.','L4' : '','L5' : ''}
F34={'L1' : ' The one you','L2' : 'love is closer','L3' : 'than you think.','L4' : '','L5' : ''}
F35={'L1' : ' Love always and','L2' : 'deeply.','L3' : '','L4' : '','L5' : ''}
F36={'L1' : ' Your heart will','L2' : 'always make','L3' : 'itself known','L4' : 'through your','L5' : 'words.'}
F37={'L1' : ' Love is like','L2' : 'wildflowers...it','L3' : 'is often found','L4' : 'in the most','L5' : 'unlikely places.'}
F38={'L1' : ' Love is the','L2' : 'only medicine','L3' : 'for a broken','L4' : 'heart.','L5' : ''}
F39={'L1' : ' Love is the','L2' : 'triumph of','L3' : 'imagination over','L4' : 'intelligence.','L5' : '--H.L. Mencken'}
F40={'L1' : ' Much more grows','L2' : 'in the garden','L3' : 'than that which','L4' : 'is planted','L5' : 'there.'}
F41={'L1' : ' Only love lets','L2' : 'us see normal','L3' : 'things in an','L4' : 'extraordinary','L5' : 'way.'}
F42={'L1' : ' The greatest','L2' : 'gift is love.','L3' : '','L4' : '','L5' : ''}
F43={'L1' : ' Those who have','L2' : 'love, have','L3' : 'wealth beyond','L4' : 'measure.','L5' : ''}
F44={'L1' : ' To love is to','L2' : 'forgive.','L3' : '','L4' : '','L5' : ''}
F45={'L1' : ' Hearts are not','L2' : 'to be had as a','L3' : 'gift, hearts are','L4' : 'to be earned.','L5' : '--W.B. Yeats'}
F46={'L1' : ' Your heart is a','L2' : 'place to draw','L3' : 'true happiness.','L4' : '','L5' : ''}
F47={'L1' : ' Love conquers','L2' : 'all.','L3' : '','L4' : '','L5' : ''}
F48={'L1' : ' Count your','L2' : 'blessings by','L3' : 'thinking of','L4' : 'those whom you','L5' : 'love.'}
F49={'L1' : ' Welcome is a','L2' : 'powerful word.','L3' : '','L4' : '','L5' : ''}
F50={'L1' : ' A dubious','L2' : 'friend may be an','L3' : 'enemy in','L4' : 'camouflage.','L5' : ''}
F51={'L1' : ' A feather in','L2' : 'the hand is','L3' : 'better than a','L4' : 'bird in the air.','L5' : ''}
F52={'L1' : ' A fresh start','L2' : 'will put you on','L3' : 'your way.','L4' : '','L5' : ''}
F53={'L1' : ' A hunch is','L2' : 'creativity','L3' : 'trying to tell','L4' : 'you something.','L5' : ''}
F54={'L1' : ' A light heart','L2' : 'carries you','L3' : 'through all the','L4' : 'hard times.','L5' : ''}
F55={'L1' : ' A new','L2' : 'perspective will','L3' : 'come with the','L4' : 'new year.','L5' : ''}
F56={'L1' : ' A person is','L2' : 'never too old to','L3' : 'learn.','L4' : '','L5' : ''}
F57={'L1' : ' A person of','L2' : 'words and not','L3' : 'deeds is like a','L4' : 'garden full of','L5' : 'weeds.'}
F58={'L1' : ' A pleasant','L2' : 'surprise is','L3' : 'waiting for you.','L4' : '','L5' : ''}
F59={'L1' : ' A smooth long','L2' : 'journey! Great','L3' : 'expectations.','L4' : '','L5' : ''}
F60={'L1' : ' A soft voice','L2' : 'may be awfully','L3' : 'persuasive.','L4' : '','L5' : ''}
F61={'L1' : ' A truly rich','L2' : 'life contains','L3' : 'love and art in','L4' : 'abundance.','L5' : ''}
F62={'L1' : ' Adventure can','L2' : 'be real','L3' : 'happiness.','L4' : '','L5' : ''}
F63={'L1' : ' All the effort','L2' : 'you are making','L3' : 'will ultimately','L4' : 'pay off.','L5' : ''}
F64={'L1' : ' All the','L2' : 'troubles you','L3' : 'have will pass','L4' : 'away very','L5' : 'quickly.'}
F65={'L1' : ' All will go','L2' : 'well with your','L3' : 'new project.','L4' : '','L5' : ''}
F66={'L1' : ' Allow','L2' : 'compassion to','L3' : 'guide your','L4' : 'decisions.','L5' : ''}
F67={'L1' : ' An agreeable','L2' : 'romance might','L3' : 'begin to take on','L4' : 'the appearance.','L5' : ''}
F68={'L1' : ' An important','L2' : 'person will','L3' : 'offer you','L4' : 'support.','L5' : ''}
F69={'L1' : ' An inch of time','L2' : 'is an inch of','L3' : 'gold.','L4' : '','L5' : ''}
F70={'L1' : ' Be careful or','L2' : 'you could fall','L3' : 'for some tricks','L4' : 'today.','L5' : ''}
F71={'L1' : ' Beauty in its','L2' : 'various forms','L3' : 'appeals to you.','L4' : '','L5' : ''}
F72={'L1' : ' Because you','L2' : 'demand more from','L3' : 'yourself, others','L4' : 'respect you','L5' : 'deeply.'}
F73={'L1' : ' Believe in','L2' : 'yourself and','L3' : 'others will too.','L4' : '','L5' : ''}
F74={'L1' : ' Better ask','L2' : 'twice than lose','L3' : 'yourself once.','L4' : '','L5' : ''}
F75={'L1' : ' Carve your name','L2' : 'on your heart','L3' : 'and not on','L4' : 'marble.','L5' : ''}
F76={'L1' : ' Change is','L2' : 'happening in','L3' : 'your life, so go','L4' : 'with the flow!','L5' : ''}
F77={'L1' : ' Competence like','L2' : 'yours is','L3' : 'underrated.','L4' : '','L5' : ''}
F78={'L1' : '','L2' : 'Congratulations!','L3' : 'You are on your','L4' : 'way.','L5' : ''}
F79={'L1' : ' Could I get','L2' : 'some directions','L3' : 'to your heart?','L4' : '','L5' : ''}
F80={'L1' : ' Courtesy begins','L2' : 'in the home.','L3' : '','L4' : '','L5' : ''}
F81={'L1' : ' Courtesy is','L2' : 'contagious.','L3' : '','L4' : '','L5' : ''}
F82={'L1' : ' Curiosity kills','L2' : 'boredom. Nothing','L3' : 'can kill','L4' : 'curiosity.','L5' : ''}
F83={'L1' : ' Dedicate','L2' : 'yourself with a','L3' : 'calm mind to the','L4' : 'task at hand.','L5' : ''}
F84={'L1' : ' Depart not from','L2' : 'the path which','L3' : 'fate has you','L4' : 'assigned.','L5' : ''}
F85={'L1' : ' Determination','L2' : 'is what you need','L3' : 'now.','L4' : '','L5' : ''}
F86={'L1' : ' Disbelief','L2' : 'destroys the','L3' : 'magic.','L4' : '','L5' : ''}
F87={'L1' : ' Distance','L2' : 'yourself from','L3' : 'the vain.','L4' : '','L5' : ''}
F88={'L1' : ' Do not be','L2' : 'intimidated by','L3' : 'the eloquence of','L4' : 'others.','L5' : ''}
F89={'L1' : ' Do not let','L2' : 'ambitions','L3' : 'overshadow small','L4' : 'success.','L5' : ''}
F90={'L1' : ' Do not make','L2' : 'extra work for','L3' : 'yourself.','L4' : '','L5' : ''}
F91={'L1' : ' Dont confuse','L2' : 'recklessness','L3' : 'with confidence.','L4' : '','L5' : ''}
F92={'L1' : ' Dont just','L2' : 'think, act!','L3' : '','L4' : '','L5' : ''}
F93={'L1' : ' Dont let','L2' : 'friends impose','L3' : 'on you, work','L4' : 'calmly and','L5' : 'silently.'}
F94={'L1' : ' Dont let the','L2' : 'past and useless','L3' : 'detail choke','L4' : 'your existence.','L5' : ''}
F95={'L1' : ' Dont let your','L2' : 'limitations','L3' : 'overshadow your','L4' : 'talents.','L5' : ''}
F96={'L1' : ' Dont worry;','L2' : 'prosperity will','L3' : 'knock on your','L4' : 'door soon.','L5' : ''}
F97={'L1' : ' Each day,','L2' : 'compel yourself','L3' : 'to do something','L4' : 'you would rather','L5' : 'not do.'}
F98={'L1' : ' Education is','L2' : 'the ability to','L3' : 'meet lifes','L4' : 'situations.','L5' : ''}
F99={'L1' : ' Emulate what','L2' : 'you admire in','L3' : 'your parents.','L4' : '','L5' : ''}
F100={'L1' : ' Emulate what','L2' : 'you respect in','L3' : 'your friends.','L4' : '','L5' : ''}
F101={'L1' : ' Every flower','L2' : 'blooms in its','L3' : 'own sweet time.','L4' : '','L5' : ''}
F102={'L1' : ' Every wise man','L2' : 'started out by','L3' : 'asking many','L4' : 'questions.','L5' : ''}
F103={'L1' : ' Everyday in','L2' : 'your life is a','L3' : 'special','L4' : 'occasion.','L5' : ''}
F104={'L1' : ' Failure is the','L2' : 'chance to do','L3' : 'better next','L4' : 'time.','L5' : ''}
F105={'L1' : ' Feeding a cow','L2' : 'with roses does','L3' : 'not get extra','L4' : 'appreciation.','L5' : ''}
F106={'L1' : ' For hate is','L2' : 'never conquered','L3' : 'by hate. Hate is','L4' : 'conquered by','L5' : 'love.'}
F107={'L1' : ' Fortune Not','L2' : 'Found: Abort,','L3' : 'Retry, Ignore?','L4' : '','L5' : ''}
F108={'L1' : ' From listening','L2' : 'comes wisdom and','L3' : 'from speaking','L4' : 'repentance.','L5' : ''}
F109={'L1' : ' From now on','L2' : 'your kindness','L3' : 'will lead you to','L4' : 'success.','L5' : ''}
F110={'L1' : ' Get your mind','L2' : 'set...confidence','L3' : 'will lead you','L4' : 'on.','L5' : ''}
F111={'L1' : ' Go take a rest;','L2' : 'you deserve it.','L3' : '','L4' : '','L5' : ''}
F112={'L1' : ' Good news will','L2' : 'be brought to','L3' : 'you by mail.','L4' : '','L5' : ''}
F113={'L1' : ' Good news will','L2' : 'come to you by','L3' : 'mail.','L4' : '','L5' : ''}
F114={'L1' : ' Good to begin','L2' : 'well, better to','L3' : 'end well.','L4' : '','L5' : ''}
F115={'L1' : ' Happiness','L2' : 'begins with','L3' : 'facing life with','L4' : 'a smile and a','L5' : 'wink.'}
F116={'L1' : ' Happiness will','L2' : 'bring you good','L3' : 'luck.','L4' : '','L5' : ''}
F117={'L1' : ' Have a','L2' : 'beautiful day.','L3' : '','L4' : '','L5' : ''}
F118={'L1' : ' He who expects','L2' : 'no gratitude','L3' : 'shall never be','L4' : 'disappointed.','L5' : ''}
F119={'L1' : ' He who knows he','L2' : 'has enough is','L3' : 'rich.','L4' : '','L5' : ''}
F120={'L1' : ' Help! Im being','L2' : 'held prisoner in','L3' : 'a chinese','L4' : 'bakery!','L5' : ''}
F121={'L1' : ' How you look','L2' : 'depends on where','L3' : 'you go.','L4' : '','L5' : ''}
F122={'L1' : ' I learn by','L2' : 'going where I','L3' : 'have to go.','L4' : '','L5' : ''}
F123={'L1' : ' If a true sense','L2' : 'of value is to','L3' : 'be yours it must','L4' : 'come through','L5' : 'service.'}
F124={'L1' : ' If certainty','L2' : 'were truth, we','L3' : 'would never be','L4' : 'wrong.','L5' : ''}
F125={'L1' : ' If you look in','L2' : 'the right','L3' : 'places, you can','L4' : 'find some good','L5' : 'offerings.'}
F126={'L1' : ' If your desires','L2' : 'are not to','L3' : 'extravagant they','L4' : 'will be granted.','L5' : ''}
F127={'L1' : ' In order to','L2' : 'take, one must','L3' : 'first give.','L4' : '','L5' : ''}
F128={'L1' : ' In the end all','L2' : 'things will be','L3' : 'known.','L4' : '','L5' : ''}
F129={'L1' : ' It could be','L2' : 'better, but its','L3' : 'good enough.','L4' : '','L5' : ''}
F130={'L1' : ' It is better to','L2' : 'deal with','L3' : 'problems before','L4' : 'they arise.','L5' : ''}
F131={'L1' : ' It is worth','L2' : 'reviewing some','L3' : 'old lessons.','L4' : '','L5' : ''}
F132={'L1' : ' It takes','L2' : 'courage to admit','L3' : 'fault.','L4' : '','L5' : ''}
F133={'L1' : ' Its time to get','L2' : 'moving. Your','L3' : 'spirits will','L4' : 'lift','L5' : 'accordingly.'}
F134={'L1' : ' Keep your face','L2' : 'to the sunshine','L3' : 'and you will','L4' : 'never see','L5' : 'shadows.'}
F135={'L1' : ' Let the world','L2' : 'be filled with','L3' : 'tranquility and','L4' : 'goodwill.','L5' : ''}
F136={'L1' : ' Listen not to','L2' : 'vain words of','L3' : 'empty tongue.','L4' : '','L5' : ''}
F137={'L1' : ' Listen to','L2' : 'everyone. Ideas','L3' : 'come from','L4' : 'everywhere.','L5' : ''}
F138={'L1' : ' Living with a','L2' : 'commitment to','L3' : 'excellence shall','L4' : 'take you far.','L5' : ''}
F139={'L1' : ' Love is a warm','L2' : 'fire to keep the','L3' : 'soul warm.','L4' : '','L5' : ''}
F140={'L1' : ' Love is like','L2' : 'sweet medicine,','L3' : 'good to the last','L4' : 'drop.','L5' : ''}
F141={'L1' : ' Love lights up','L2' : 'the world.','L3' : '','L4' : '','L5' : ''}
F142={'L1' : ' Love truth, but','L2' : 'pardon error.','L3' : '','L4' : '','L5' : ''}
F143={'L1' : ' Man is born to','L2' : 'live and not','L3' : 'prepared to','L4' : 'live.','L5' : ''}
F144={'L1' : ' Many will','L2' : 'travel to hear','L3' : 'you speak.','L4' : '','L5' : ''}
F145={'L1' : ' Meditation with','L2' : 'an old enemy is','L3' : 'advised.','L4' : '','L5' : ''}
F146={'L1' : ' Miles are','L2' : 'covered one step','L3' : 'at a time.','L4' : '','L5' : ''}
F147={'L1' : ' Never fear! The','L2' : 'end of something','L3' : 'marks the start','L4' : 'of something','L5' : 'new.'}
F148={'L1' : ' New ideas could','L2' : 'be profitable.','L3' : '','L4' : '','L5' : ''}
F149={'L1' : ' New people will','L2' : 'bring you new','L3' : 'realizations,','L4' : 'especially about','L5' : 'big issues.'}
F150={'L1' : ' No one can walk','L2' : 'backwards into','L3' : 'the future.','L4' : '','L5' : ''}
