F1={'L1' : ' Contentment','L2' : 'will be your key','L3' : 'to happiness.','L4' : '','L5' : ''}
F2={'L1' : ' Cope with','L2' : 'current','L3' : 'pressures','L4' : 'without losing','L5' : 'your cool.'}
F3={'L1' : ' Counting time','L2' : 'is not as','L3' : 'important as','L4' : 'making time','L5' : 'count.'}
F4={'L1' : ' Courage  and','L2' : 'optimism are','L3' : 'your best','L4' : 'traits.','L5' : ''}
F5={'L1' : ' Deal only with','L2' : 'firms of proven','L3' : 'reliability.','L4' : '','L5' : ''}
F6={'L1' : ' Decide what you','L2' : 'want and go for','L3' : 'it.','L4' : '','L5' : ''}
F7={'L1' : ' Desires that','L2' : 'are not','L3' : 'extravagant will','L4' : 'be granted.','L5' : ''}
F8={'L1' : ' Diversify your','L2' : 'interests for','L3' : 'fewer worries.','L4' : '','L5' : ''}
F9={'L1' : ' Dont be hasty;','L2' : 'prosperity will','L3' : 'knock on your','L4' : 'door soon.','L5' : ''}
F10={'L1' : ' Dont forget,','L2' : 'you are always','L3' : 'on our minds.','L4' : '','L5' : ''}
F11={'L1' : ' Dont lose sight','L2' : 'of what you','L3' : 'want.','L4' : '','L5' : ''}
F12={'L1' : ' Dont steal, the','L2' : 'government hates','L3' : 'competition.','L4' : '','L5' : ''}
F13={'L1' : ' Doors shall','L2' : 'soon open for','L3' : 'you.','L4' : '','L5' : ''}
F14={'L1' : ' Easy times are','L2' : 'ahead for you.','L3' : '','L4' : '','L5' : ''}
F15={'L1' : ' Energy will','L2' : 'abound next','L3' : 'month.','L4' : '','L5' : ''}
F16={'L1' : ' Enjoy the good','L2' : 'luck a companion','L3' : 'brings you.','L4' : '','L5' : ''}
F17={'L1' : ' Enjoy your good','L2' : 'company, they','L3' : 'are true','L4' : 'friends.','L5' : ''}
F18={'L1' : ' Everything','L2' : 'takes longer','L3' : 'than you think.','L4' : '','L5' : ''}
F19={'L1' : ' Executive','L2' : 'ability in your','L3' : 'makeup will lead','L4' : 'you to success.','L5' : ''}
F20={'L1' : ' Fall shall see','L2' : 'all your cares','L3' : 'and worries slip','L4' : 'away.','L5' : ''}
F21={'L1' : ' Family','L2' : 'relationships','L3' : 'will improve','L4' : 'with time.','L5' : ''}
F22={'L1' : ' Feelings of','L2' : 'goodwill to all','L3' : 'should lighten','L4' : 'your mood.','L5' : ''}
F23={'L1' : ' Few women admit','L2' : 'their age. Few','L3' : 'men act theirs.','L4' : '','L5' : ''}
F24={'L1' : ' Financial','L2' : 'security is just','L3' : 'around the','L4' : 'corner.','L5' : ''}
F25={'L1' : ' Financial','L2' : 'success is on','L3' : 'your doorstep.','L4' : '','L5' : ''}
F26={'L1' : ' Find some time','L2' : 'to look up some','L3' : 'older relatives.','L4' : '','L5' : ''}
F27={'L1' : ' Find the road','L2' : 'to your','L3' : 'happiness by','L4' : 'helping others.','L5' : ''}
F28={'L1' : ' Follow the','L2' : 'advice of your','L3' : 'heart.','L4' : '','L5' : ''}
F29={'L1' : ' Follow your','L2' : 'instincts, they','L3' : 'are valid.','L4' : '','L5' : ''}
F30={'L1' : ' Following inner','L2' : 'promptings','L3' : 'brings quiet','L4' : 'accomplishment.','L5' : ''}
F31={'L1' : ' Fortune is on','L2' : 'your side. Play','L3' : 'it for all its','L4' : 'worth.','L5' : ''}
F32={'L1' : ' Fortune smiles','L2' : 'upon you at this','L3' : 'time.','L4' : '','L5' : ''}
F33={'L1' : ' Fruits of your','L2' : 'labour will be','L3' : 'rich and sweet','L4' : 'indeed.','L5' : ''}
F34={'L1' : ' Fun and','L2' : 'excitement will','L3' : 'soon be yours.','L4' : '','L5' : ''}
F35={'L1' : ' Functioning','L2' : 'superbly will','L3' : 'come','L4' : 'automatically to','L5' : 'you.'}
F36={'L1' : ' Get to the','L2' : 'nitty-gritty of','L3' : 'things in all','L4' : 'dealings.','L5' : ''}
F37={'L1' : ' Get together','L2' : 'with associates','L3' : 'for beneficial','L4' : 'decisions.','L5' : ''}
F38={'L1' : ' Get your','L2' : 'schedule into a','L3' : 'shape you can','L4' : 'manage easily.','L5' : ''}
F39={'L1' : ' Give it time','L2' : 'and it will work','L3' : 'out.','L4' : '','L5' : ''}
F40={'L1' : ' Give time and','L2' : 'thought to','L3' : 'everything you','L4' : 'do.','L5' : ''}
F41={'L1' : ' Give your','L2' : 'business','L3' : 'interests top','L4' : 'priority next','L5' : 'month.'}
F42={'L1' : ' Give your','L2' : 'undivided','L3' : 'attention to','L4' : 'things that are','L5' : 'basic.'}
F43={'L1' : ' Go easy, be','L2' : 'moderate and','L3' : 'patient.','L4' : '','L5' : ''}
F44={'L1' : ' Golden','L2' : 'investment','L3' : 'opportunities','L4' : 'are arising.','L5' : ''}
F45={'L1' : ' Good common','L2' : 'sense will help','L3' : 'you master life.','L4' : '','L5' : ''}
F46={'L1' : ' Good fortune','L2' : 'will soon find','L3' : 'you.','L4' : '','L5' : ''}
F47={'L1' : ' Good news is on','L2' : 'the way.','L3' : '','L4' : '','L5' : ''}
F48={'L1' : ' Good news will','L2' : 'come to you from','L3' : 'far away.','L4' : '','L5' : ''}
F49={'L1' : ' Good things are','L2' : 'said about you.','L3' : '','L4' : '','L5' : ''}
F50={'L1' : ' Good things','L2' : 'come in small','L3' : 'packages.','L4' : '','L5' : ''}
F51={'L1' : ' Great thoughts','L2' : 'will come from','L3' : 'the heart.','L4' : '','L5' : ''}
F52={'L1' : ' Happy events','L2' : 'will take place','L3' : 'shortly in your','L4' : 'home.','L5' : ''}
F53={'L1' : ' Heaven will','L2' : 'rain success on','L3' : 'you.','L4' : '','L5' : ''}
F54={'L1' : ' Home','L2' : 'entertainment','L3' : 'ought to be','L4' : 'extra successful','L5' : 'now.'}
F55={'L1' : ' Ideas are like','L2' : 'children; there','L3' : 'are none so','L4' : 'wonderful as','L5' : 'your own.'}
F56={'L1' : ' If bargain','L2' : 'hunting, be','L3' : 'practical.','L4' : '','L5' : ''}
F57={'L1' : ' If ignorance is','L2' : 'bliss, you must','L3' : 'be orgasmic.','L4' : '','L5' : ''}
F58={'L1' : ' If planning','L2' : 'study or','L3' : 'training, now is','L4' : 'the time to go','L5' : 'ahead.'}
F59={'L1' : ' If you have any','L2' : 'doubts at all,','L3' : 'hold off on','L4' : 'decisions.','L5' : ''}
F60={'L1' : ' If you have','L2' : 'money in hand,','L3' : 'spend it on','L4' : 'improving','L5' : 'yourself.'}
F61={'L1' : ' If you work','L2' : 'seriously, you','L3' : 'will succeed.','L4' : '','L5' : ''}
F62={'L1' : ' Important','L2' : 'associates will','L3' : 'be there for you','L4' : 'if needed.','L5' : ''}
F63={'L1' : ' Important','L2' : 'decisions must','L3' : 'be made, dont','L4' : 'avoid making','L5' : 'them.'}
F64={'L1' : ' Important news','L2' : 'about your job','L3' : 'will come soon.','L4' : '','L5' : ''}
F65={'L1' : ' Indulge your','L2' : 'ambitious','L3' : 'nature.','L4' : '','L5' : ''}
F66={'L1' : ' It will take','L2' : 'maturity and','L3' : 'compromise to','L4' : 'manage.','L5' : ''}
F67={'L1' : ' Joint ventures','L2' : 'work out better','L3' : 'than going it','L4' : 'alone.','L5' : ''}
F68={'L1' : ' Joy will come','L2' : 'with the return','L3' : 'of a dear','L4' : 'friend.','L5' : ''}
F69={'L1' : ' Judge one not','L2' : 'by his charms,','L3' : 'but by his','L4' : 'qualities.','L5' : ''}
F70={'L1' : ' Keep a','L2' : 'go-for-it','L3' : 'attitude and you','L4' : 'are sure to be a','L5' : 'winner.'}
F71={'L1' : ' Keep','L2' : 'expectations','L3' : 'reasonable.','L4' : '','L5' : ''}
F72={'L1' : ' Let intuition','L2' : 'rule this month,','L3' : 'and you will','L4' : 'find success.','L5' : ''}
F73={'L1' : ' Let no one','L2' : 'cause you to','L3' : 'violate your','L4' : 'principles.','L5' : ''}
F74={'L1' : ' Life is not a','L2' : 'struggle, its a','L3' : 'wiggle.','L4' : '','L5' : ''}
F75={'L1' : ' Life will','L2' : 'shower happiness','L3' : 'upon you.','L4' : '','L5' : ''}
F76={'L1' : ' Look deeply','L2' : 'within to root','L3' : 'out negative','L4' : 'attitudes.','L5' : ''}
F77={'L1' : ' Look for a','L2' : 'priceless bit of','L3' : 'news from a','L4' : 'loved one.','L5' : ''}
F78={'L1' : ' Look for new','L2' : 'outlets for your','L3' : 'own creative','L4' : 'abilities.','L5' : ''}
F79={'L1' : ' Look for some','L2' : 'bargains this','L3' : 'month.','L4' : '','L5' : ''}
F80={'L1' : ' Look to the','L2' : 'coming month for','L3' : 'a solution to','L4' : 'your problem.','L5' : ''}
F81={'L1' : ' Love begets','L2' : 'love.','L3' : '','L4' : '','L5' : ''}
F82={'L1' : ' Listen to your','L2' : 'intuition this','L3' : 'month.','L4' : '','L5' : ''}
F83={'L1' : ' Love is like','L2' : 'wildflowers; it','L3' : 'is often found','L4' : 'in the most','L5' : 'unlikely places.'}
F84={'L1' : ' Love is the','L2' : 'triumph of horny','L3' : 'over smart.','L4' : '','L5' : ''}
F85={'L1' : ' Luck begins to','L2' : 'soar as high as','L3' : 'your ambition.','L4' : '','L5' : ''}
F86={'L1' : ' Luck is on your','L2' : 'side if you have','L3' : 'patience.','L4' : '','L5' : ''}
F87={'L1' : ' Luck is on your','L2' : 'side this month.','L3' : '','L4' : '','L5' : ''}
F88={'L1' : ' Luck will soon','L2' : 'visit you.','L3' : '','L4' : '','L5' : ''}
F89={'L1' : ' Luck will visit','L2' : 'you on the next','L3' : 'new moon.','L4' : '','L5' : ''}
F90={'L1' : ' Luck with your','L2' : 'job and money','L3' : 'will put you','L4' : 'into good','L5' : 'humour.'}
F91={'L1' : ' Make allowances','L2' : 'for exaggeration','L3' : 'on someones','L4' : 'part.','L5' : ''}
F92={'L1' : ' Make no rash','L2' : 'moves for now.','L3' : '','L4' : '','L5' : ''}
F93={'L1' : ' Make the most','L2' : 'of a period of','L3' : 'relative peace','L4' : 'and harmony.','L5' : ''}
F94={'L1' : ' Make two grins','L2' : 'grow where there','L3' : 'was only a','L4' : 'grouch before.','L5' : ''}
F95={'L1' : ' Make up your','L2' : 'mind and do what','L3' : 'you want to do.','L4' : '','L5' : ''}
F96={'L1' : ' Make use of','L2' : 'whatever','L3' : 'advanced','L4' : 'technology is','L5' : 'available.'}
F97={'L1' : ' Make way for','L2' : 'new career','L3' : 'decisions.','L4' : '','L5' : ''}
F98={'L1' : ' Many a false','L2' : 'step is made by','L3' : 'standing still.','L4' : '','L5' : ''}
F99={'L1' : ' Many ideals are','L2' : 'becoming real.','L3' : '','L4' : '','L5' : ''}
F100={'L1' : ' May life throw','L2' : 'you a pleasant','L3' : 'curve.','L4' : '','L5' : ''}
F101={'L1' : ' Minimize','L2' : 'expectations to','L3' : 'avoid being','L4' : 'disappointed.','L5' : ''}
F102={'L1' : ' Moneywise, you','L2' : 'are lucky this','L3' : 'month.','L4' : '','L5' : ''}
F103={'L1' : ' More money and','L2' : 'travel is in','L3' : 'your future.','L4' : '','L5' : ''}
F104={'L1' : ' Move slowly but','L2' : 'surely to','L3' : 'success.','L4' : '','L5' : ''}
F105={'L1' : ' New financial','L2' : 'resources will','L3' : 'soon become','L4' : 'available to','L5' : 'you.'}
F106={'L1' : ' Next month will','L2' : 'be a special','L3' : 'month for you.','L4' : '','L5' : ''}
F107={'L1' : ' Next month will','L2' : 'be hectic, yet','L3' : 'delightful.','L4' : '','L5' : ''}
F108={'L1' : ' Next month will','L2' : 'prove to be','L3' : 'pivotal in your','L4' : 'life.','L5' : ''}
F109={'L1' : ' Next week you','L2' : 'should unveil','L3' : 'your idea. Be','L4' : 'ready to act.','L5' : ''}
F110={'L1' : ' Next month you','L2' : 'will be a big','L3' : 'hit socially.','L4' : '','L5' : ''}
F111={'L1' : ' Now is a good','L2' : 'time to start','L3' : 'something new.','L4' : '','L5' : ''}
F112={'L1' : ' Now is the','L2' : 'time.','L3' : '','L4' : '','L5' : ''}
F113={'L1' : ' Now is the time','L2' : 'to depart from','L3' : 'your regular','L4' : 'routine.','L5' : ''}
F114={'L1' : ' Now is the time','L2' : 'to enjoy trying','L3' : 'something new.','L4' : '','L5' : ''}
F115={'L1' : ' Now is the time','L2' : 'to resolve all','L3' : 'unfinished','L4' : 'business.','L5' : ''}
F116={'L1' : ' Now is the time','L2' : 'to set','L3' : 'priorities.','L4' : '','L5' : ''}
F117={'L1' : ' Now is the time','L2' : 'to set your','L3' : 'sights high and','L4' : 'go for it.','L5' : ''}
F118={'L1' : ' Now is the time','L2' : 'to try something','L3' : 'new.','L4' : '','L5' : ''}
F119={'L1' : ' Old','L2' : 'acquaintances','L3' : 'are important','L4' : 'this week.','L5' : ''}
F120={'L1' : ' On the first','L2' : 'week of the next','L3' : 'month do','L4' : 'something just','L5' : 'for you.'}
F121={'L1' : ' Opportunities','L2' : 'to shine in your','L3' : 'career will','L4' : 'materialize','L5' : 'soon.'}
F122={'L1' : ' Optimism &','L2' : 'versatility are','L3' : 'your strengths.','L4' : '','L5' : ''}
F123={'L1' : ' Others thought','L2' : 'waves are easy','L3' : 'to tune into','L4' : 'now.','L5' : ''}
F124={'L1' : ' Past','L2' : 'inspirations &','L3' : 'experiences will','L4' : 'be helpful in','L5' : 'your job.'}
F125={'L1' : ' People will','L2' : 'listen to you','L3' : 'and could be','L4' : 'willing to help.','L5' : ''}
F126={'L1' : ' People you deal','L2' : 'with will be','L3' : 'more','L4' : 'co-operative','L5' : 'than usual.'}
F127={'L1' : ' Persistence','L2' : 'will lead to a','L3' : 'promotion soon.','L4' : '','L5' : ''}
F128={'L1' : ' Play it safe','L2' : 'next month, and','L3' : 'it will be a','L4' : 'great one.','L5' : ''}
F129={'L1' : ' Prosperity &','L2' : 'love are in','L3' : 'reach.','L4' : '','L5' : ''}
F130={'L1' : ' Recreational','L2' : 'interests may','L3' : 'command your','L4' : 'attention.','L5' : ''}
F131={'L1' : ' Re-decorating','L2' : 'will be in your','L3' : 'plans.','L4' : '','L5' : ''}
F132={'L1' : ' Relax and','L2' : 'concentrate on','L3' : 'your career','L4' : 'plans.','L5' : ''}
F133={'L1' : ' Relax and','L2' : 'romance will','L3' : 'flourish.','L4' : '','L5' : ''}
F134={'L1' : ' Relax and spend','L2' : 'some time with a','L3' : 'loved one.','L4' : '','L5' : ''}
F135={'L1' : ' Rely on long','L2' : 'time friends to','L3' : 'give you advice.','L4' : '','L5' : ''}
F136={'L1' : ' Research shall','L2' : 'bring','L3' : 'considerable','L4' : 'success with','L5' : 'great results.'}
F137={'L1' : ' Resist a','L2' : 'temptation to','L3' : 'take shortcuts','L4' : 'of any kind.','L5' : ''}
F138={'L1' : ' Revisit old','L2' : 'friends, it has','L3' : 'been far too','L4' : 'long.','L5' : ''}
F139={'L1' : ' Romantic','L2' : 'interests will','L3' : 'improve if you','L4' : 'make the next','L5' : 'move.'}
F140={'L1' : ' Rough times are','L2' : 'now behind you.','L3' : '','L4' : '','L5' : ''}
F141={'L1' : ' Saturday night','L2' : 'promises great','L3' : 'excitement.','L4' : '','L5' : ''}
F142={'L1' : ' Seek to','L2' : 'establish your','L3' : 'inner sense of','L4' : 'serenity.','L5' : ''}
F143={'L1' : ' Seize the day.','L2' : 'Fortune says you','L3' : 'can have it all.','L4' : '','L5' : ''}
F144={'L1' : ' Sensitivity','L2' : 'makes you','L3' : 'special, but','L4' : 'also makes you','L5' : 'vulnerable.'}
F145={'L1' : ' Seven & eight','L2' : 'are significant','L3' : 'numbers for you.','L4' : '','L5' : ''}
F146={'L1' : ' Sing and','L2' : 'rejoice; fortune','L3' : 'is smiling upon','L4' : 'you.','L5' : ''}
F147={'L1' : ' Simplicity &','L2' : 'clarity in dress','L3' : 'will draw','L4' : 'desired eyes','L5' : 'your way.'}
F148={'L1' : ' Socially, you','L2' : 'will be involved','L3' : 'with an','L4' : 'enjoyable event.','L5' : ''}
F149={'L1' : ' Solutions will','L2' : 'come to you','L3' : 'while you are','L4' : 'walking.','L5' : ''}
F150={'L1' : ' Someone close','L2' : 'to you will show','L3' : 'you the way.','L4' : '','L5' : ''}
