F1={'L1' : ' You will have','L2' : 'good luck in the','L3' : 'winter.','L4' : '','L5' : ''}
F2={'L1' : ' Your fortune is','L2' : 'not something to','L3' : 'find but to','L4' : 'unfold.','L5' : ''}
F3={'L1' : ' Do onto others','L2' : 'as you with','L3' : 'others do onto','L4' : 'you.','L5' : ''}
F4={'L1' : ' Your home will','L2' : 'be visited by','L3' : 'good health and','L4' : 'wealth.','L5' : ''}
F5={'L1' : ' For every','L2' : 'minute spent in','L3' : 'organizing, an','L4' : 'hour is earned.','L5' : ''}
F6={'L1' : ' Even a stopped','L2' : 'clock is right','L3' : 'twice a day.','L4' : '','L5' : ''}
F7={'L1' : ' Life is a play;','L2' : 'its not its','L3' : 'length but its','L4' : 'performance that','L5' : 'counts.'}
F8={'L1' : ' Deal with the','L2' : 'faults of others','L3' : 'as gently as','L4' : 'with your own.','L5' : ''}
F9={'L1' : ' Love is like','L2' : 'war: easy to','L3' : 'begin, but very','L4' : 'hard to stop.','L5' : ''}
F10={'L1' : ' If I had you,','L2' : 'the money, fame,','L3' : 'and fortune','L4' : 'never could','L5' : 'compete.'}
F11={'L1' : ' You display the','L2' : 'wonderful traits','L3' : 'of charm and','L4' : 'courtesy.','L5' : ''}
F12={'L1' : ' Over-indulgence','L2' : 'hinders body and','L3' : 'mind.','L4' : '','L5' : ''}
F13={'L1' : ' Romance is','L2' : 'about to','L3' : 'blossom.','L4' : '','L5' : ''}
F14={'L1' : ' Do it because','L2' : 'you love it.','L3' : '','L4' : '','L5' : ''}
F15={'L1' : ' A mans fortune','L2' : 'has its form','L3' : 'given to it by','L4' : 'his habits.','L5' : ''}
F16={'L1' : ' Learn to enjoy','L2' : 'every minute of','L3' : 'your life.','L4' : '','L5' : ''}
F17={'L1' : ' You outdistance','L2' : 'all competitors.','L3' : '','L4' : '','L5' : ''}
F18={'L1' : ' Fortune favors','L2' : 'the bold.','L3' : '--Virgil','L4' : '','L5' : ''}
F19={'L1' : ' Its a great','L2' : 'weekend to watch','L3' : 'a movie.','L4' : '','L5' : ''}
F20={'L1' : ' An interesting','L2' : 'musical','L3' : 'opportunity is','L4' : 'in your near','L5' : 'future.'}
F21={'L1' : ' If you obey all','L2' : 'the rules, you','L3' : 'miss all the','L4' : 'fun.','L5' : ''}
F22={'L1' : ' Just believe','L2' : 'it: water and','L3' : 'oil cannot be','L4' : 'mixed.','L5' : ''}
F23={'L1' : ' We can learn','L2' : 'much from wise','L3' : 'words and less','L4' : 'from wise guys.','L5' : ''}
F24={'L1' : ' Find a peaceful','L2' : 'place where you','L3' : 'can make plans','L4' : 'for the future.','L5' : ''}
F25={'L1' : ' Your existence','L2' : 'contributes','L3' : 'positively to','L4' : 'mankind.','L5' : ''}
F26={'L1' : ' A four-wheeled','L2' : 'adventure will','L3' : 'soon bring you','L4' : 'happiness.','L5' : ''}
F27={'L1' : ' You will find','L2' : 'hidden treasures','L3' : 'where least','L4' : 'expected.','L5' : ''}
F28={'L1' : ' A beautiful,','L2' : 'smart, and','L3' : 'loving person','L4' : 'will be coming','L5' : 'into your life.'}
F29={'L1' : ' You are','L2' : 'affectionate and','L3' : 'loyal to those','L4' : 'you love.','L5' : ''}
F30={'L1' : ' You have great','L2' : 'physical powers','L3' : 'and an iron','L4' : 'constitution.','L5' : ''}
F31={'L1' : ' Heroism is','L2' : 'endurance for','L3' : 'one moment more.','L4' : '','L5' : ''}
F32={'L1' : ' Everyone feels','L2' : 'lucky for having','L3' : 'you as a friend.','L4' : '','L5' : ''}
F33={'L1' : ' Patience is the','L2' : 'key to joy!','L3' : '','L4' : '','L5' : ''}
F34={'L1' : ' The dumplings','L2' : 'you just ate','L3' : 'will','L4' : 'self-destruct in','L5' : '3...2...1...'}
F35={'L1' : ' You would be','L2' : 'wise to keep','L3' : 'your eyes wide','L4' : 'open at all','L5' : 'times.'}
F36={'L1' : ' Share yourself','L2' : 'and your','L3' : 'possessions with','L4' : 'close friends.','L5' : ''}
F37={'L1' : ' To find your','L2' : 'self, think for','L3' : 'yourself.','L4' : '','L5' : ''}
F38={'L1' : ' You will soon','L2' : 'make an','L3' : 'important','L4' : 'decision.','L5' : ''}
F39={'L1' : ' A new romance','L2' : 'is in the near','L3' : 'future.','L4' : '','L5' : ''}
F40={'L1' : ' If you want to','L2' : 'be loved, be','L3' : 'lovable.','L4' : '','L5' : ''}
F41={'L1' : ' Fortune does','L2' : 'not change men,','L3' : 'it unmasks them.','L4' : '','L5' : ''}
F42={'L1' : ' Explore your','L2' : 'own world by','L3' : 'working together','L4' : 'with friends.','L5' : ''}
F43={'L1' : ' Passionate new','L2' : 'romance appears','L3' : 'in your life','L4' : 'when you least','L5' : 'expect it.'}
F44={'L1' : ' Those who bring','L2' : 'sunshine to the','L3' : 'lives of others','L4' : 'cannot keep it','L5' : 'from themselves.'}
F45={'L1' : ' Sharing little','L2' : 'joys offers','L3' : 'great hope to','L4' : 'others.','L5' : ''}
F46={'L1' : ' For success','L2' : 'today look first','L3' : 'to yourself.','L4' : '','L5' : ''}
F47={'L1' : ' Your sense of','L2' : 'humor reveals','L3' : 'itself at just','L4' : 'the right times!','L5' : ''}
F48={'L1' : ' Apply yourself','L2' : 'to the basics','L3' : 'and progress','L4' : 'will follow.','L5' : ''}
F49={'L1' : ' Nothing gets in','L2' : 'the way of your','L3' : 'vision of','L4' : 'yourself in the','L5' : 'future.'}
F50={'L1' : ' Time is the','L2' : 'wisest','L3' : 'counselor.','L4' : '','L5' : ''}
F51={'L1' : ' Culture and','L2' : 'customs of China','L3' : 'attract you.','L4' : '','L5' : ''}
F52={'L1' : ' The architect','L2' : 'of your destiny','L3' : 'is yourself.','L4' : '','L5' : ''}
F53={'L1' : ' Praise a fine','L2' : 'day at night.','L3' : '','L4' : '','L5' : ''}
F54={'L1' : ' Doing what you','L2' : 'love is freedom.','L3' : ' Loving what you','L4' : 'do is happiness.','L5' : ''}
F55={'L1' : ' He deserves','L2' : 'paradise who','L3' : 'makes his','L4' : 'companions','L5' : 'laugh.'}
F56={'L1' : ' Success is in','L2' : 'the details.','L3' : '','L4' : '','L5' : ''}
F57={'L1' : ' Nothing in the','L2' : 'world is','L3' : 'difficult if one','L4' : 'sets his mind to','L5' : 'it.'}
F58={'L1' : ' Home is where','L2' : 'your heart is.','L3' : '','L4' : '','L5' : ''}
F59={'L1' : ' Life is a','L2' : 'tragedy for','L3' : 'those who feel','L4' : 'and a comedy for','L5' : 'those who think.'}
F60={'L1' : ' You are tasting','L2' : 'the sweets of','L3' : 'success.','L4' : '','L5' : ''}
F61={'L1' : ' You have much','L2' : 'skill in','L3' : 'expressing','L4' : 'yourself to be','L5' : 'effective.'}
F62={'L1' : ' He who has good','L2' : 'health is young.','L3' : '','L4' : '','L5' : ''}
F63={'L1' : ' Pardon is the','L2' : 'choicest flower','L3' : 'of victory.','L4' : '','L5' : ''}
F64={'L1' : ' People say you','L2' : 'have sharp sense','L3' : 'and superb','L4' : 'intellect.','L5' : ''}
F65={'L1' : ' Two small jumps','L2' : 'are sometimes','L3' : 'better than one','L4' : 'big leap.','L5' : ''}
F66={'L1' : ' Do what is','L2' : 'right, not what','L3' : 'you should.','L4' : '','L5' : ''}
F67={'L1' : ' Tastes like','L2' : 'chicken.','L3' : '','L4' : '','L5' : ''}
F68={'L1' : ' You are broad','L2' : 'minded and','L3' : 'socially active.','L4' : '','L5' : ''}
F69={'L1' : ' Win as if you','L2' : 'were used to it,','L3' : 'lose as if you','L4' : 'enjoyed it for a','L5' : 'change.'}
F70={'L1' : ' Everything you','L2' : 'add to the truth','L3' : 'subtracts from','L4' : 'the truth.','L5' : ''}
F71={'L1' : ' Be cautious','L2' : 'while walking in','L3' : 'darkness alone.','L4' : '','L5' : ''}
F72={'L1' : ' Anyone who','L2' : 'dares to be, can','L3' : 'never be weak.','L4' : '','L5' : ''}
F73={'L1' : ' Love is the','L2' : 'glue that holds','L3' : 'together','L4' : 'everything in','L5' : 'the world.'}
F74={'L1' : ' You are strong','L2' : 'and brave.','L3' : '','L4' : '','L5' : ''}
F75={'L1' : ' Every important','L2' : 'call is a close','L3' : 'one.','L4' : '','L5' : ''}
F76={'L1' : ' Be confident','L2' : 'and you will','L3' : 'succeed.','L4' : '','L5' : ''}
F77={'L1' : ' Your destiny','L2' : 'lies before you,','L3' : 'choose wisely.','L4' : '','L5' : ''}
F78={'L1' : ' Cleverness is','L2' : 'serviceable for','L3' : 'everything,','L4' : 'sufficient for','L5' : 'nothing.'}
F79={'L1' : ' You have the','L2' : 'rare ability to','L3' : 'recognize','L4' : 'ability in','L5' : 'others.'}
F80={'L1' : ' Welcome each','L2' : 'day as a fresh','L3' : 'new beginning.','L4' : '','L5' : ''}
F81={'L1' : ' You have a','L2' : 'natural grace','L3' : 'and','L4' : 'consideration','L5' : 'for others.'}
F82={'L1' : ' You are never','L2' : 'bitter,','L3' : 'deceptive, or','L4' : 'petty.','L5' : ''}
F83={'L1' : ' You make other','L2' : 'people realize','L3' : 'that there exist','L4' : 'other beauties','L5' : 'in the world.'}
F84={'L1' : ' Try a new','L2' : 'system or a','L3' : 'different','L4' : 'approach.','L5' : ''}
F85={'L1' : ' Keep on','L2' : 'charging the','L3' : 'enemy so long as','L4' : 'there is life.','L5' : ''}
F86={'L1' : ' The only','L2' : 'certainty is','L3' : 'that nothing is','L4' : 'certain.','L5' : ''}
F87={'L1' : ' With care and','L2' : 'understanding,','L3' : 'your life will','L4' : 'have no','L5' : 'obstacles.'}
F88={'L1' : ' Everything has','L2' : 'beauty but not','L3' : 'everyone sees','L4' : 'it.','L5' : ''}
F89={'L1' : ' Travel','L2' : 'hopefully;','L3' : 'arrive','L4' : 'expectantly.','L5' : ''}
F90={'L1' : ' You long to see','L2' : 'the great','L3' : 'pyramids in','L4' : 'Egypt.','L5' : ''}
F91={'L1' : ' Fear is the','L2' : 'root of all','L3' : 'evil.','L4' : '','L5' : ''}
F92={'L1' : ' With a little','L2' : 'more hard work,','L3' : 'you creativity','L4' : 'takes you to','L5' : 'great heights.'}
F93={'L1' : ' You are the','L2' : 'captain of your','L3' : 'soul.','L4' : '','L5' : ''}
F94={'L1' : ' A great fortune','L2' : 'in the hands of','L3' : 'a fool is a','L4' : 'great','L5' : 'misfortune.'}
F95={'L1' : ' Talent is not a','L2' : 'rare commodity;','L3' : 'discipline is.','L4' : '','L5' : ''}
F96={'L1' : ' Become your own','L2' : 'muse.','L3' : '','L4' : '','L5' : ''}
F97={'L1' : ' You have an','L2' : 'iron will, which','L3' : 'helps you','L4' : 'succeed in','L5' : 'everything.'}
F98={'L1' : ' You have the','L2' : 'ability to','L3' : 'analyze and','L4' : 'solve any','L5' : 'problem.'}
F99={'L1' : ' Dance like no','L2' : 'one is watching.','L3' : '','L4' : '','L5' : ''}
F100={'L1' : ' Wear sunscreen.','L2' : '','L3' : '','L4' : '','L5' : ''}
F101={'L1' : ' You will be','L2' : 'Told about it','L3' : 'Tomorrow. Go','L4' : 'Home and Prepare','L5' : 'Thyself.'}
F102={'L1' : ' Bank error in','L2' : 'your favor.','L3' : 'Collect $200.','L4' : '','L5' : ''}
F103={'L1' : ' Your goose is','L2' : 'cooked. (Your','L3' : 'current chick is','L4' : 'burned up too!)','L5' : ''}
F104={'L1' : ' You could live','L2' : 'a better life,','L3' : 'if you had a','L4' : 'better mind and','L5' : 'a better body.'}
F105={'L1' : ' Are you sure','L2' : 'the back door is','L3' : 'locked?','L4' : '','L5' : ''}
F106={'L1' : ' Be security','L2' : 'conscious --','L3' : 'National defense','L4' : 'is at stake.','L5' : ''}
F107={'L1' : ' Dont you wish','L2' : 'you had more','L3' : 'energy... or','L4' : 'less ambition?','L5' : ''}
F108={'L1' : ' Writing is','L2' : 'turning ones','L3' : 'worst moments','L4' : 'into money. --','L5' : 'J.P. Donleavy'}
F109={'L1' : ' You enjoy the','L2' : 'company of other','L3' : 'people.','L4' : '','L5' : ''}
F110={'L1' : ' It may or may','L2' : 'not be','L3' : 'worthwhile, but','L4' : 'it still has to','L5' : 'be done.'}
F111={'L1' : ' You look tired.','L2' : '','L3' : '','L4' : '','L5' : ''}
F112={'L1' : ' You are','L2' : 'fairminded, just','L3' : 'and loving.','L4' : '','L5' : ''}
F113={'L1' : ' Good day for a','L2' : 'change of scene.','L3' : 'Repaper the','L4' : 'bedroom wall.','L5' : ''}
F114={'L1' : ' You are','L2' : 'fighting for','L3' : 'survival in your','L4' : 'own sweet and','L5' : 'gentle way.'}
F115={'L1' : ' You have an','L2' : 'ability to sense','L3' : 'and know higher','L4' : 'truth.','L5' : ''}
F116={'L1' : ' You are taking','L2' : 'yourself far too','L3' : 'seriously.','L4' : '','L5' : ''}
F117={'L1' : ' Tomorrow will','L2' : 'be cancelled due','L3' : 'to lack of','L4' : 'interest.','L5' : ''}
F118={'L1' : ' Your society','L2' : 'will be sought','L3' : 'by people of','L4' : 'taste and','L5' : 'refinement.'}
F119={'L1' : ' Q: Why did the','L2' : 'germ cross the','L3' : 'microscope? A:','L4' : 'To get to the','L5' : 'other slide.'}
F120={'L1' : ' Make a wish, it','L2' : 'might come true.','L3' : '','L4' : '','L5' : ''}
F121={'L1' : ' Many changes of','L2' : 'mind and mood;','L3' : 'do not hesitate','L4' : 'too long.','L5' : ''}
F122={'L1' : ' Expect a letter','L2' : 'from a friend','L3' : 'who will ask a','L4' : 'favor of you.','L5' : ''}
F123={'L1' : ' Today is the','L2' : 'first day of the','L3' : 'rest of your','L4' : 'life.','L5' : ''}
F124={'L1' : ' You will reach','L2' : 'the highest','L3' : 'possible point','L4' : 'in your business','L5' : 'or profession.'}
F125={'L1' : ' Excellent time','L2' : 'to become a','L3' : 'missing person.','L4' : '','L5' : ''}
F126={'L1' : ' Youre almost as','L2' : 'happy as you','L3' : 'think you are.','L4' : '','L5' : ''}
F127={'L1' : ' Truth will out','L2' : 'this morning.','L3' : '(Which may','L4' : 'really mess','L5' : 'things up.)'}
F128={'L1' : ' You will become','L2' : 'rich and famous','L3' : 'unless you dont.','L4' : '','L5' : ''}
F129={'L1' : ' You are sick,','L2' : 'twisted and','L3' : 'perverted. I','L4' : 'like that in a','L5' : 'person.'}
F130={'L1' : ' You will be the','L2' : 'victim of a','L3' : 'bizarre joke.','L4' : '','L5' : ''}
F131={'L1' : ' Be cheerful','L2' : 'while you are','L3' : 'alive. --','L4' : 'Phathotep, 24th','L5' : 'Century B.C.'}
F132={'L1' : ' Your sister','L2' : 'swims out to','L3' : 'meet troop','L4' : 'ships.','L5' : ''}
F133={'L1' : ' Youre not my','L2' : 'type. For that','L3' : 'matter, youre','L4' : 'not even my','L5' : 'species!!!'}
F134={'L1' : ' You are capable','L2' : 'of planning your','L3' : 'future.','L4' : '','L5' : ''}
F135={'L1' : ' Beware of','L2' : 'Bigfoot!','L3' : '','L4' : '','L5' : ''}
F136={'L1' : ' You have a','L2' : 'truly strong','L3' : 'individuality.','L4' : '','L5' : ''}
F137={'L1' : ' Dont worry so','L2' : 'loud, your','L3' : 'roommate cant','L4' : 'think.','L5' : ''}
F138={'L1' : ' A visit to a','L2' : 'fresh place will','L3' : 'bring strange','L4' : 'work.','L5' : ''}
F139={'L1' : ' Be careful! Is','L2' : 'it classified?','L3' : '','L4' : '','L5' : ''}
F140={'L1' : ' Beware of a','L2' : 'tall blond man','L3' : 'with one black','L4' : 'shoe.','L5' : ''}
F141={'L1' : ' Change your','L2' : 'thoughts and you','L3' : 'change your','L4' : 'world.','L5' : ''}
F142={'L1' : ' Youre at the','L2' : 'end of the road','L3' : 'again.','L4' : '','L5' : ''}
F143={'L1' : ' Q: What is','L2' : 'purple and','L3' : 'commutes? A: An','L4' : 'Abelian grape.','L5' : ''}
F144={'L1' : ' You will be','L2' : 'awarded a medal','L3' : 'for disregarding','L4' : 'safety in saving','L5' : 'someone.'}
F145={'L1' : ' You will be','L2' : 'given a post of','L3' : 'trust and','L4' : 'responsibility.','L5' : ''}
F146={'L1' : ' You will be','L2' : 'aided greatly by','L3' : 'a person whom','L4' : 'you thought to','L5' : 'be unimportant.'}
F147={'L1' : ' You have the','L2' : 'power to','L3' : 'influence all','L4' : 'with whom you','L5' : 'come in contact.'}
F148={'L1' : ' You will be','L2' : 'winged by an','L3' : 'anti-aircraft','L4' : 'battery.','L5' : ''}
F149={'L1' : ' Q: How was','L2' : 'Thomas J. Watson','L3' : 'buried? A: 9','L4' : 'edge down.','L5' : ''}
F150={'L1' : ' You can rent','L2' : 'this space for','L3' : 'only $5 a week.','L4' : '','L5' : ''}
