F1={'L1' : ' Dont relax! Its','L2' : 'only your','L3' : 'tension thats','L4' : 'holding you','L5' : 'together.'}
F2={'L1' : ' You seek to','L2' : 'shield those you','L3' : 'love and you','L4' : 'like the role of','L5' : 'the provider.'}
F3={'L1' : ' You are so','L2' : 'boring that when','L3' : 'I see you my','L4' : 'feet go to','L5' : 'sleep.'}
F4={'L1' : ' Try to value','L2' : 'useful qualities','L3' : 'in one who loves','L4' : 'you.','L5' : ''}
F5={'L1' : ' You are always','L2' : 'busy.','L3' : '','L4' : '','L5' : ''}
F6={'L1' : ' Q: How many','L2' : 'Martians does it','L3' : 'take to screw in','L4' : 'a light bulb? A:','L5' : 'One and a half.'}
F7={'L1' : ' Bridge ahead.','L2' : 'Pay troll.','L3' : '','L4' : '','L5' : ''}
F8={'L1' : ' Is this really','L2' : 'happening?','L3' : '','L4' : '','L5' : ''}
F9={'L1' : ' Try the Moo Shu','L2' : 'Pork. It is','L3' : 'especially good','L4' : 'today.','L5' : ''}
F10={'L1' : ' You are the','L2' : 'only person to','L3' : 'ever get this','L4' : 'message.','L5' : ''}
F11={'L1' : ' You will','L2' : 'overcome the','L3' : 'attacks of','L4' : 'jealous','L5' : 'associates.'}
F12={'L1' : ' Your nature','L2' : 'demands love and','L3' : 'your happiness','L4' : 'depends on it.','L5' : ''}
F13={'L1' : ' You will obey','L2' : 'or molten silver','L3' : 'will be poured','L4' : 'into your ears.','L5' : ''}
F14={'L1' : ' What happened','L2' : 'last night can','L3' : 'happen again.','L4' : '','L5' : ''}
F15={'L1' : ' Domestic','L2' : 'happiness and','L3' : 'faithful','L4' : 'friends.','L5' : ''}
F16={'L1' : ' Dont worry.','L2' : 'Lifes too long.','L3' : '-- Vincent','L4' : 'Sardi, Jr.','L5' : ''}
F17={'L1' : ' You will be','L2' : 'called upon to','L3' : 'help a friend in','L4' : 'trouble.','L5' : ''}
F18={'L1' : ' Q: Why did the','L2' : 'WASP cross the','L3' : 'road? A: To get','L4' : 'to the middle.','L5' : ''}
F19={'L1' : ' Dont read','L2' : 'everything you','L3' : 'believe.','L4' : '','L5' : ''}
F20={'L1' : ' Celebrate','L2' : 'Hannibal Day','L3' : 'this year. Take','L4' : 'an elephant to','L5' : 'lunch.'}
F21={'L1' : ' Dont look back,','L2' : 'the lemmings are','L3' : 'gaining on you.','L4' : '','L5' : ''}
F22={'L1' : ' So this is it.','L2' : 'Were going to','L3' : 'die.','L4' : '','L5' : ''}
F23={'L1' : ' Fine day for','L2' : 'friends. So-so','L3' : 'day for you.','L4' : '','L5' : ''}
F24={'L1' : ' You will be','L2' : 'divorced within','L3' : 'a year.','L4' : '','L5' : ''}
F25={'L1' : ' If you stand on','L2' : 'your head, you','L3' : 'will get','L4' : 'footprints in','L5' : 'your hair.'}
F26={'L1' : ' You have taken','L2' : 'yourself too','L3' : 'seriously.','L4' : '','L5' : ''}
F27={'L1' : ' You will hear','L2' : 'good news from','L3' : 'one you thought','L4' : 'unfriendly to','L5' : 'you.'}
F28={'L1' : ' You have had a','L2' : 'long-term','L3' : 'stimulation','L4' : 'relative to','L5' : 'business.'}
F29={'L1' : ' Somethings','L2' : 'rotten in the','L3' : 'state of','L4' : 'Denmark. --','L5' : 'Shakespeare'}
F30={'L1' : ' Suspicion','L2' : 'always haunts','L3' : 'the guilty mind.','L4' : '-- Wm.','L5' : 'Shakespeare'}
F31={'L1' : ' Today is','L2' : 'National','L3' : 'Existential','L4' : 'Ennui Awareness','L5' : 'Day.'}
F32={'L1' : ' If you sow your','L2' : 'wild oats, hope','L3' : 'for a crop','L4' : 'failure.','L5' : ''}
F33={'L1' : ' You will be the','L2' : 'last person to','L3' : 'buy a Chrysler.','L4' : '','L5' : ''}
F34={'L1' : ' Youd like to do','L2' : 'it','L3' : 'instantaneously,','L4' : 'but thats too','L5' : 'slow.'}
F35={'L1' : ' An avocado-tone','L2' : 'refrigerator','L3' : 'would look good','L4' : 'on your resume.','L5' : ''}
F36={'L1' : ' You will get','L2' : 'what you','L3' : 'deserve.','L4' : '','L5' : ''}
F37={'L1' : ' Todays','L2' : 'weirdness is','L3' : 'tomorrows reason','L4' : 'why. -- Hunter','L5' : 'S. Thompson'}
F38={'L1' : ' Time to be','L2' : 'aggressive. Go','L3' : 'after a tattooed','L4' : 'Virgo.','L5' : ''}
F39={'L1' : ' Your aims are','L2' : 'high, and you','L3' : 'are capable of','L4' : 'much.','L5' : ''}
F40={'L1' : ' You teach best','L2' : 'what you most','L3' : 'need to learn.','L4' : '','L5' : ''}
F41={'L1' : ' You worry too','L2' : 'much about your','L3' : 'job. Stop it.','L4' : 'You are not paid','L5' : 'enough to worry.'}
F42={'L1' : ' Stay away from','L2' : 'flying saucers','L3' : 'today.','L4' : '','L5' : ''}
F43={'L1' : ' Chicken Little','L2' : 'only has to be','L3' : 'right once.','L4' : '','L5' : ''}
F44={'L1' : ' Never commit','L2' : 'yourself! Let','L3' : 'someone else','L4' : 'commit you.','L5' : ''}
F45={'L1' : ' Its a very','L2' : '*__UN*lucky','L3' : 'week in which to','L4' : 'be took dead. --','L5' : 'Churchy La Femme'}
F46={'L1' : ' That secret','L2' : 'youve been','L3' : 'guarding, isnt.','L4' : '','L5' : ''}
F47={'L1' : ' Beware of a','L2' : 'tall black man','L3' : 'with one blond','L4' : 'shoe.','L5' : ''}
F48={'L1' : ' Avoid reality','L2' : 'at all costs.','L3' : '','L4' : '','L5' : ''}
F49={'L1' : ' Your aim is','L2' : 'high and to the','L3' : 'right.','L4' : '','L5' : ''}
F50={'L1' : ' Questionable','L2' : 'day. Ask','L3' : 'somebody','L4' : 'something.','L5' : ''}
F51={'L1' : ' Q: How do you','L2' : 'stop an elephant','L3' : 'from charging?','L4' : 'A: Take away his','L5' : 'credit cards.'}
F52={'L1' : ' You dont become','L2' : 'a failure until','L3' : 'youre satisfied','L4' : 'with being one.','L5' : ''}
F53={'L1' : ' Your boss is a','L2' : 'few sandwiches','L3' : 'short of a','L4' : 'picnic.','L5' : ''}
F54={'L1' : ' Your lucky','L2' : 'number has been','L3' : 'disconnected.','L4' : '','L5' : ''}
F55={'L1' : ' You will','L2' : 'triumph over','L3' : 'your enemy.','L4' : '','L5' : ''}
F56={'L1' : ' Exercise','L2' : 'caution in your','L3' : 'daily affairs.','L4' : '','L5' : ''}
F57={'L1' : ' Youre a card','L2' : 'which will have','L3' : 'to be dealt','L4' : 'with.','L5' : ''}
F58={'L1' : ' You have an','L2' : 'ambitious nature','L3' : 'and may make a','L4' : 'name for','L5' : 'yourself.'}
F59={'L1' : ' Live in a world','L2' : 'of your own, but','L3' : 'always welcome','L4' : 'visitors.','L5' : ''}
F60={'L1' : ' Q: Why did the','L2' : 'chicken cross','L3' : 'the road? A: He','L4' : 'was giving it','L5' : 'last rites.'}
F61={'L1' : ' You may be','L2' : 'recognized soon.','L3' : 'Hide.','L4' : '','L5' : ''}
F62={'L1' : ' You look like a','L2' : 'million dollars.','L3' : 'All green and','L4' : 'wrinkled.','L5' : ''}
F63={'L1' : ' You will meet','L2' : 'an important','L3' : 'person who will','L4' : 'help you advance','L5' : 'professionally.'}
F64={'L1' : ' You will','L2' : 'receive a legacy','L3' : 'which will place','L4' : 'you above want.','L5' : ''}
F65={'L1' : ' You have been','L2' : 'selected for a','L3' : 'secret mission.','L4' : '','L5' : ''}
F66={'L1' : ' Beware of','L2' : 'low-flying','L3' : 'butterflies.','L4' : '','L5' : ''}
F67={'L1' : ' A gift of a','L2' : 'flower will soon','L3' : 'be made to you.','L4' : '','L5' : ''}
F68={'L1' : ' Love is in the','L2' : 'offing. Be','L3' : 'affectionate to','L4' : 'one who adores','L5' : 'you.'}
F69={'L1' : ' You will be','L2' : 'awarded some','L3' : 'great honor.','L4' : '','L5' : ''}
F70={'L1' : ' Dont go surfing','L2' : 'in South Dakota','L3' : 'for a while.','L4' : '','L5' : ''}
F71={'L1' : ' You have','L2' : 'literary talent','L3' : 'that you should','L4' : 'take pains to','L5' : 'develop.'}
F72={'L1' : ' You will gain','L2' : 'money by a','L3' : 'speculation or','L4' : 'lottery.','L5' : ''}
F73={'L1' : ' Do not sleep in','L2' : 'a eucalyptus','L3' : 'tree tonight.','L4' : '','L5' : ''}
F74={'L1' : ' You will','L2' : 'pioneer the','L3' : 'first Martian','L4' : 'colony.','L5' : ''}
F75={'L1' : ' Someone whom','L2' : 'you reject','L3' : 'today, will','L4' : 'reject you','L5' : 'tomorrow.'}
F76={'L1' : ' Your step will','L2' : 'soil many','L3' : 'countries.','L4' : '','L5' : ''}
F77={'L1' : ' You will soon','L2' : 'forget this.','L3' : '','L4' : '','L5' : ''}
F78={'L1' : ' Your object is','L2' : 'to save the','L3' : 'world, while','L4' : 'still leading a','L5' : 'pleasant life.'}
F79={'L1' : ' Good day to let','L2' : 'down old friends','L3' : 'who need help.','L4' : '','L5' : ''}
F80={'L1' : ' Just to have it','L2' : 'is enough.','L3' : '','L4' : '','L5' : ''}
F81={'L1' : ' Dont read any','L2' : 'sky-writing for','L3' : 'the next two','L4' : 'weeks.','L5' : ''}
F82={'L1' : ' Wagners music','L2' : 'is better than','L3' : 'it sounds. --','L4' : 'Mark Twain','L5' : ''}
F83={'L1' : ' Your business','L2' : 'will assume vast','L3' : 'proportions.','L4' : '','L5' : ''}
F84={'L1' : ' You now have','L2' : 'Asian Flu.','L3' : '','L4' : '','L5' : ''}
F85={'L1' : ' Dont hate','L2' : 'yourself in the','L3' : 'morning -- sleep','L4' : 'till noon.','L5' : ''}
F86={'L1' : ' A is for Apple.','L2' : '-- Hester Pryne','L3' : '','L4' : '','L5' : ''}
F87={'L1' : ' After your','L2' : 'lover has gone','L3' : 'you will still','L4' : 'have PEANUT','L5' : 'BUTTER!'}
F88={'L1' : ' Long life is in','L2' : 'store for you.','L3' : '','L4' : '','L5' : ''}
F89={'L1' : ' Youll never be','L2' : 'the man your','L3' : 'mother was!','L4' : '','L5' : ''}
F90={'L1' : ' You work very','L2' : 'hard. Dont try','L3' : 'to think as','L4' : 'well.','L5' : ''}
F91={'L1' : ' Dont look now,','L2' : 'but the man in','L3' : 'the moon is','L4' : 'laughing at you.','L5' : ''}
F92={'L1' : ' Many pages make','L2' : 'a thick book.','L3' : '','L4' : '','L5' : ''}
F93={'L1' : ' Excellent day','L2' : 'to have a rotten','L3' : 'day.','L4' : '','L5' : ''}
F94={'L1' : ' There is a 20%','L2' : 'chance of','L3' : 'tomorrow.','L4' : '','L5' : ''}
F95={'L1' : ' Your true value','L2' : 'depends entirely','L3' : 'on what you are','L4' : 'compared with.','L5' : ''}
F96={'L1' : ' Your life would','L2' : 'be very empty if','L3' : 'you had nothing','L4' : 'to regret.','L5' : ''}
F97={'L1' : ' If your life','L2' : 'was a horse,','L3' : 'youd have to','L4' : 'shoot it.','L5' : ''}
F98={'L1' : ' Q: Why did','L2' : 'Menachem Begin','L3' : 'invade Lebanon?','L4' : 'A: To impress','L5' : 'Jodie Foster.'}
F99={'L1' : ' Youre ugly and','L2' : 'your mother','L3' : 'dresses you','L4' : 'funny.','L5' : ''}
F100={'L1' : ' Excellent day','L2' : 'for putting','L3' : 'Slinkies on an','L4' : 'escalator.','L5' : ''}
F101={'L1' : ' Your boss','L2' : 'climbed the','L3' : 'corporate','L4' : 'ladder, wrong by','L5' : 'wrong.'}
F102={'L1' : ' You are','L2' : 'dishonest, but','L3' : 'never to the','L4' : 'point of hurting','L5' : 'a friend.'}
F103={'L1' : ' You will be','L2' : 'successful in','L3' : 'love.','L4' : '','L5' : ''}
F104={'L1' : ' Be cautious in','L2' : 'your daily','L3' : 'affairs.','L4' : '','L5' : ''}
F105={'L1' : ' Q: What is','L2' : 'orange and goes','L3' : 'click, click? A:','L4' : 'A ball point','L5' : 'carrot.'}
F106={'L1' : ' Among the','L2' : 'lucky, you are','L3' : 'the chosen one.','L4' : '','L5' : ''}
F107={'L1' : ' This will be a','L2' : 'memorable month','L3' : '-- no matter how','L4' : 'hard you try to','L5' : 'forget it.'}
F108={'L1' : ' Never be led','L2' : 'astray onto the','L3' : 'path of virtue.','L4' : '','L5' : ''}
F109={'L1' : ' You will be','L2' : 'held hostage by','L3' : 'a radical group.','L4' : '','L5' : ''}
F110={'L1' : ' Abandon the','L2' : 'search for','L3' : 'Truth; settle','L4' : 'for a good','L5' : 'fantasy.'}
F111={'L1' : ' Chess tonight.','L2' : '','L3' : '','L4' : '','L5' : ''}
F112={'L1' : ' Tonight you','L2' : 'will pay the','L3' : 'wages of sin;','L4' : 'Dont forget to','L5' : 'leave a tip.'}
F113={'L1' : ' Q: Whats a','L2' : 'light-year? A:','L3' : 'One-third less','L4' : 'calories than a','L5' : 'regular year.'}
F114={'L1' : ' You will live','L2' : 'to see your','L3' : 'grandchildren.','L4' : '','L5' : ''}
F115={'L1' : ' Dont get to','L2' : 'bragging.','L3' : '','L4' : '','L5' : ''}
F116={'L1' : ' Slow day.','L2' : 'Practice','L3' : 'crawling.','L4' : '','L5' : ''}
F117={'L1' : ' You will step','L2' : 'on the night','L3' : 'soil of many','L4' : 'countries.','L5' : ''}
F118={'L1' : ' Q: What lies on','L2' : 'the bottom of','L3' : 'the ocean and','L4' : 'twitches? A: A','L5' : 'nervous wreck.'}
F119={'L1' : ' Hope that the','L2' : 'day after you','L3' : 'die is a nice','L4' : 'day.','L5' : ''}
F120={'L1' : ' Do not overtax','L2' : 'your powers.','L3' : '','L4' : '','L5' : ''}
F121={'L1' : ' You will','L2' : 'probably marry','L3' : 'after a very','L4' : 'brief courtship.','L5' : ''}
F122={'L1' : ' You will be','L2' : 'audited by the','L3' : 'Internal Revenue','L4' : 'Service.','L5' : ''}
F123={'L1' : ' Q: How much','L2' : 'does it cost to','L3' : 'ride the Unibus?','L4' : 'A: 2 bits.','L5' : ''}
F124={'L1' : ' You will have','L2' : 'long and healthy','L3' : 'life.','L4' : '','L5' : ''}
F125={'L1' : ' A tall, dark','L2' : 'stranger will','L3' : 'have more fun','L4' : 'than you.','L5' : ''}
F126={'L1' : ' A visit to a','L2' : 'strange place','L3' : 'will bring fresh','L4' : 'work.','L5' : ''}
F127={'L1' : ' A vivid and','L2' : 'creative mind','L3' : 'characterizes','L4' : 'you.','L5' : ''}
F128={'L1' : ' Accent on','L2' : 'helpful side of','L3' : 'your nature.','L4' : 'Drain the moat.','L5' : ''}
F129={'L1' : ' An exotic','L2' : 'journey in','L3' : 'downtown Newark','L4' : 'is in your','L5' : 'future.'}
F130={'L1' : ' Are you a','L2' : 'turtle?','L3' : '','L4' : '','L5' : ''}
F131={'L1' : ' Avoid gunfire','L2' : 'in the bathroom','L3' : 'tonight.','L4' : '','L5' : ''}
F132={'L1' : ' Be careful!','L2' : 'UGLY strikes 9','L3' : 'out of 10!','L4' : '','L5' : ''}
F133={'L1' : ' Be different:','L2' : 'conform.','L3' : '','L4' : '','L5' : ''}
F134={'L1' : ' Be security','L2' : 'conscious --','L3' : 'National defense','L4' : 'is at stake.','L5' : ''}
F135={'L1' : ' Beauty and','L2' : 'harmony are as','L3' : 'necessary to you','L4' : 'as the very','L5' : 'breath of life.'}
F136={'L1' : ' Beware of a','L2' : 'dark-haired man','L3' : 'with a loud tie.','L4' : '','L5' : ''}
F137={'L1' : ' Caution: Keep','L2' : 'out of reach of','L3' : 'children.','L4' : '','L5' : ''}
F138={'L1' : ' Cheer Up!','L2' : 'Things are','L3' : 'getting worse at','L4' : 'a slower rate.','L5' : ''}
F139={'L1' : ' Cold hands, no','L2' : 'gloves.','L3' : '','L4' : '','L5' : ''}
F140={'L1' : ' Courage is your','L2' : 'greatest present','L3' : 'need.','L4' : '','L5' : ''}
F141={'L1' : ' Dont feed the','L2' : 'bats tonight.','L3' : '','L4' : '','L5' : ''}
F142={'L1' : ' Dont let your','L2' : 'mind wander --','L3' : 'its too little','L4' : 'to be let out','L5' : 'alone.'}
F143={'L1' : ' Dont plan any','L2' : 'hasty moves.','L3' : 'Youll be evicted','L4' : 'soon anyway.','L5' : ''}
F144={'L1' : ' Dont Worry, Be','L2' : 'Happy. -- Meher','L3' : 'Baba','L4' : '','L5' : ''}
F145={'L1' : ' Fine day to','L2' : 'work off excess','L3' : 'energy. Steal','L4' : 'something heavy.','L5' : ''}
F146={'L1' : ' Give your very','L2' : 'best today.','L3' : 'Heaven knows its','L4' : 'little enough.','L5' : ''}
F147={'L1' : ' Good news from','L2' : 'afar can bring','L3' : 'you a welcome','L4' : 'visitor.','L5' : ''}
F148={'L1' : ' Its a very','L2' : 'unlucky week in','L3' : 'which to be took','L4' : 'dead. -- Churchy','L5' : 'La Femme'}
F149={'L1' : ' Learn to pause','L2' : '-- or nothing','L3' : 'worthwhile can','L4' : 'catch up to you.','L5' : ''}
F150={'L1' : ' Let me put it','L2' : 'this way: today','L3' : 'is going to be a','L4' : 'learning','L5' : 'experience.'}
