F1={'L1' : ' Now is a good','L2' : 'time to buy','L3' : 'stock.','L4' : '','L5' : ''}
F2={'L1' : ' Now is the time','L2' : 'to go ahead and','L3' : 'pursue that love','L4' : 'interest!','L5' : ''}
F3={'L1' : ' Others can help','L2' : 'you now.','L3' : '','L4' : '','L5' : ''}
F4={'L1' : ' Pennies from','L2' : 'heaven find','L3' : 'their way to','L4' : 'your doorstep','L5' : 'this year!'}
F5={'L1' : ' Perhaps youve','L2' : 'been focusing','L3' : 'too much on','L4' : 'saving.','L5' : ''}
F6={'L1' : ' Physical','L2' : 'activity will','L3' : 'dramatically','L4' : 'improve your','L5' : 'outlook today.'}
F7={'L1' : ' Place special','L2' : 'emphasis on old','L3' : 'friendship.','L4' : '','L5' : ''}
F8={'L1' : ' Protective','L2' : 'measures will','L3' : 'prevent costly','L4' : 'disasters.','L5' : ''}
F9={'L1' : ' Remember to','L2' : 'share good','L3' : 'fortune as well','L4' : 'as bad with your','L5' : 'friends.'}
F10={'L1' : ' Rest has a','L2' : 'peaceful effect','L3' : 'on your physical','L4' : 'and emotional','L5' : 'health.'}
F11={'L1' : ' Resting well is','L2' : 'as important as','L3' : 'working hard.','L4' : '','L5' : ''}
F12={'L1' : ' Romance moves','L2' : 'you in a new','L3' : 'direction.','L4' : '','L5' : ''}
F13={'L1' : ' Savor your','L2' : 'freedom -- it is','L3' : 'precious.','L4' : '','L5' : ''}
F14={'L1' : ' Say hello to','L2' : 'others. You will','L3' : 'have a happier','L4' : 'day.','L5' : ''}
F15={'L1' : ' Self-knowledge','L2' : 'is a life long','L3' : 'process.','L4' : '','L5' : ''}
F16={'L1' : ' Sloth makes all','L2' : 'things','L3' : 'difficult;','L4' : 'industry all','L5' : 'easy.'}
F17={'L1' : ' Small','L2' : 'confidences mark','L3' : 'the onset of a','L4' : 'friendship.','L5' : ''}
F18={'L1' : ' Someone you','L2' : 'care about seeks','L3' : 'reconciliation.','L4' : '','L5' : ''}
F19={'L1' : ' Stand tall.','L2' : 'Dont look down','L3' : 'upon yourself.','L4' : '','L5' : ''}
F20={'L1' : ' Stop searching','L2' : 'forever,','L3' : 'happiness is','L4' : 'just next to','L5' : 'you.'}
F21={'L1' : ' Success is a','L2' : 'journey, not a','L3' : 'destination.','L4' : '','L5' : ''}
F22={'L1' : ' Take care and','L2' : 'sensitivity you','L3' : 'show towards','L4' : 'others will','L5' : 'return to you.'}
F23={'L1' : ' Take the high','L2' : 'road.','L3' : '','L4' : '','L5' : ''}
F24={'L1' : ' The austerity','L2' : 'you see around','L3' : 'you covers the','L4' : 'richness of life','L5' : 'like a veil.'}
F25={'L1' : ' The best','L2' : 'prediction of','L3' : 'future is the','L4' : 'past.','L5' : ''}
F26={'L1' : ' The first man','L2' : 'gets the oyster,','L3' : 'the second man','L4' : 'gets the shell.','L5' : ''}
F27={'L1' : ' The harder you','L2' : 'work, the','L3' : 'luckier you get.','L4' : '','L5' : ''}
F28={'L1' : ' The night life','L2' : 'is for you.','L3' : '','L4' : '','L5' : ''}
F29={'L1' : ' The one that','L2' : 'recognizes the','L3' : 'illusion does','L4' : 'not act as if it','L5' : 'is real.'}
F30={'L1' : ' The only people','L2' : 'who never fail','L3' : 'are those who','L4' : 'never try.','L5' : ''}
F31={'L1' : ' The person who','L2' : 'will not stand','L3' : 'for something','L4' : 'will fall for','L5' : 'anything.'}
F32={'L1' : ' The philosophy','L2' : 'of one century','L3' : 'is the common','L4' : 'sense of the','L5' : 'next.'}
F33={'L1' : ' The saints are','L2' : 'the sinners who','L3' : 'keep on trying.','L4' : '','L5' : ''}
F34={'L1' : ' The secret to','L2' : 'good friends is','L3' : 'no secret to','L4' : 'you.','L5' : ''}
F35={'L1' : ' The small','L2' : 'courtesies','L3' : 'sweeten life,','L4' : 'the greater','L5' : 'ennoble it.'}
F36={'L1' : ' The sure way to','L2' : 'predict the','L3' : 'future is to','L4' : 'invent it.','L5' : ''}
F37={'L1' : ' The truly','L2' : 'generous share,','L3' : 'even with the','L4' : 'undeserving.','L5' : ''}
F38={'L1' : ' The weather is','L2' : 'wonderful.','L3' : '','L4' : '','L5' : ''}
F39={'L1' : ' There is no','L2' : 'mistake so great','L3' : 'as that of being','L4' : 'always right.','L5' : ''}
F40={'L1' : ' There is no','L2' : 'wisdom greater','L3' : 'than kindness.','L4' : '','L5' : ''}
F41={'L1' : ' There is no','L2' : 'greater pleasure','L3' : 'than seeing your','L4' : 'loved ones','L5' : 'prosper.'}
F42={'L1' : ' Theres no such','L2' : 'thing as an','L3' : 'ordinary cat.','L4' : '','L5' : ''}
F43={'L1' : ' Those who care','L2' : 'will make the','L3' : 'effort.','L4' : '','L5' : ''}
F44={'L1' : ' Time and','L2' : 'patience are','L3' : 'called for; many','L4' : 'surprises await','L5' : 'you!'}
F45={'L1' : ' Time is','L2' : 'precious, but','L3' : 'truth is more','L4' : 'precious than','L5' : 'time'}
F46={'L1' : ' To know','L2' : 'oneself, one','L3' : 'should assert','L4' : 'oneself.','L5' : ''}
F47={'L1' : ' Today is the','L2' : 'conserve','L3' : 'yourself, as','L4' : 'things just wont','L5' : 'budge.'}
F48={'L1' : ' Today, your','L2' : 'mouth might be','L3' : 'moving but no','L4' : 'one is','L5' : 'listening.'}
F49={'L1' : ' Tonight you','L2' : 'will be blinded','L3' : 'by passion.','L4' : '','L5' : ''}
F50={'L1' : ' Use your','L2' : 'eloquence where','L3' : 'it will do the','L4' : 'most good.','L5' : ''}
F51={'L1' : ' Welcome change.','L2' : '','L3' : '','L4' : '','L5' : ''}
F52={'L1' : ' Well done is','L2' : 'better than well','L3' : 'said.','L4' : '','L5' : ''}
F53={'L1' : ' Whats hidden in','L2' : 'an empty box?','L3' : '','L4' : '','L5' : ''}
F54={'L1' : ' Whats yours in','L2' : 'mine, and whats','L3' : 'mine is mine.','L4' : '','L5' : ''}
F55={'L1' : ' When your heart','L2' : 'is pure, your','L3' : 'mind is clear.','L4' : '','L5' : ''}
F56={'L1' : ' Wish you','L2' : 'happiness.','L3' : '','L4' : '','L5' : ''}
F57={'L1' : ' You always','L2' : 'bring others','L3' : 'happiness.','L4' : '','L5' : ''}
F58={'L1' : ' You are a','L2' : 'person of','L3' : 'another time.','L4' : '','L5' : ''}
F59={'L1' : ' You are a','L2' : 'talented','L3' : 'storyteller.','L4' : '','L5' : ''}
F60={'L1' : ' You are admired','L2' : 'by everyone for','L3' : 'your talent and','L4' : 'ability.','L5' : ''}
F61={'L1' : ' You are almost','L2' : 'there.','L3' : '','L4' : '','L5' : ''}
F62={'L1' : ' You are busy,','L2' : 'but you are','L3' : 'happy.','L4' : '','L5' : ''}
F63={'L1' : ' You are going','L2' : 'to have some new','L3' : 'clothes.','L4' : '','L5' : ''}
F64={'L1' : ' You are in good','L2' : 'hands this','L3' : 'evening.','L4' : '','L5' : ''}
F65={'L1' : ' You are','L2' : 'open-minded and','L3' : 'quick to make','L4' : 'new friends.','L5' : ''}
F66={'L1' : ' You are solid','L2' : 'and dependable.','L3' : '','L4' : '','L5' : ''}
F67={'L1' : ' You are working','L2' : 'hard.','L3' : '','L4' : '','L5' : ''}
F68={'L1' : ' You desire','L2' : 'recognition and','L3' : 'you will find','L4' : 'it.','L5' : ''}
F69={'L1' : ' You have a deep','L2' : 'interest in all','L3' : 'that is','L4' : 'artistic.','L5' : ''}
F70={'L1' : ' You have a','L2' : 'friendly heart','L3' : 'and are well','L4' : 'admired.','L5' : ''}
F71={'L1' : ' You have a','L2' : 'shrewd knack for','L3' : 'spotting','L4' : 'insincerity.','L5' : ''}
F72={'L1' : ' You have a','L2' : 'yearning for','L3' : 'perfection.','L4' : '','L5' : ''}
F73={'L1' : ' You have an','L2' : 'active mind and','L3' : 'a keen','L4' : 'imagination.','L5' : ''}
F74={'L1' : ' You have','L2' : 'exceeded what','L3' : 'was expected.','L4' : '','L5' : ''}
F75={'L1' : ' You have the','L2' : 'power to write','L3' : 'your own','L4' : 'fortune.','L5' : ''}
F76={'L1' : ' You have','L2' : 'yearning for','L3' : 'perfection.','L4' : '','L5' : ''}
F77={'L1' : ' You love','L2' : 'challenge.','L3' : '','L4' : '','L5' : ''}
F78={'L1' : ' You make people','L2' : 'realize that','L3' : 'there exist','L4' : 'other beauties','L5' : 'in the world.'}
F79={'L1' : ' You never','L2' : 'hesitate to','L3' : 'tackle the most','L4' : 'difficult','L5' : 'problems.'}
F80={'L1' : ' You seek to','L2' : 'shield those you','L3' : 'love and like','L4' : 'the role of','L5' : 'provider.'}
F81={'L1' : ' You understand','L2' : 'how to have fun','L3' : 'with others and','L4' : 'to enjoy your','L5' : 'solitude.'}
F82={'L1' : ' You will be a','L2' : 'great success','L3' : 'both in the','L4' : 'business world','L5' : 'and society.'}
F83={'L1' : ' You will be','L2' : 'blessed with','L3' : 'longevity.','L4' : '','L5' : ''}
F84={'L1' : ' You will be','L2' : 'unusually','L3' : 'successful in','L4' : 'business.','L5' : ''}
F85={'L1' : ' You will become','L2' : 'a great','L3' : 'philanthropist','L4' : 'in your later','L5' : 'years.'}
F86={'L1' : ' You will enjoy','L2' : 'good health.','L3' : '','L4' : '','L5' : ''}
F87={'L1' : ' You will have a','L2' : 'fine capacity','L3' : 'for the','L4' : 'enjoyment of','L5' : 'life.'}
F88={'L1' : ' You will make','L2' : 'change for the','L3' : 'better.','L4' : '','L5' : ''}
F89={'L1' : ' Your abilities','L2' : 'are','L3' : 'unparalleled.','L4' : '','L5' : ''}
F90={'L1' : ' Your ability is','L2' : 'appreciated.','L3' : '','L4' : '','L5' : ''}
F91={'L1' : ' Your biggest','L2' : 'virtue is your','L3' : 'modesty.','L4' : '','L5' : ''}
F92={'L1' : ' Your character','L2' : 'can be described','L3' : 'as natural and','L4' : 'unrestrained.','L5' : ''}
F93={'L1' : ' Your','L2' : 'difficulties','L3' : 'will strengthen','L4' : 'you.','L5' : ''}
F94={'L1' : ' Your dreams are','L2' : 'never silly;','L3' : 'depend on them','L4' : 'to guide you.','L5' : ''}
F95={'L1' : ' Your dreams are','L2' : 'worth your best','L3' : 'efforts to','L4' : 'achieve them.','L5' : ''}
F96={'L1' : ' Your energy','L2' : 'returns and you','L3' : 'get things done.','L4' : '','L5' : ''}
F97={'L1' : ' Your first love','L2' : 'has never','L3' : 'forgotten you.','L4' : '','L5' : ''}
F98={'L1' : ' Your happiness','L2' : 'is before you,','L3' : 'not behind you!','L4' : 'Cherish it.','L5' : ''}
F99={'L1' : ' Your home is','L2' : 'the center of','L3' : 'great love.','L4' : '','L5' : ''}
F100={'L1' : ' Your ideals are','L2' : 'well within your','L3' : 'reach.','L4' : '','L5' : ''}
F101={'L1' : ' Your infinite','L2' : 'capacity for','L3' : 'patience will be','L4' : 'rewarded sooner','L5' : 'or later.'}
F102={'L1' : ' Your leadership','L2' : 'qualities will','L3' : 'be tested and','L4' : 'proven.','L5' : ''}
F103={'L1' : ' Your life will','L2' : 'get more and','L3' : 'more exciting.','L4' : '','L5' : ''}
F104={'L1' : ' Your love of','L2' : 'music will be an','L3' : 'important part','L4' : 'of your life.','L5' : ''}
F105={'L1' : ' Your mind is','L2' : 'your greatest','L3' : 'asset.','L4' : '','L5' : ''}
F106={'L1' : ' Your quick wits','L2' : 'will get you out','L3' : 'of a tough','L4' : 'situation.','L5' : ''}
F107={'L1' : ' Your work','L2' : 'interests can','L3' : 'capture the','L4' : 'highest status','L5' : 'or prestige.'}
F108={'L1' : ' Do not be','L2' : 'afraid of','L3' : 'competition.','L4' : '','L5' : ''}
F109={'L1' : ' An exciting','L2' : 'opportunity lies','L3' : 'ahead of you.','L4' : '','L5' : ''}
F110={'L1' : ' Sell your','L2' : 'ideas; they have','L3' : 'exceptional','L4' : 'merit.','L5' : ''}
F111={'L1' : ' You are kind','L2' : 'and friendly.','L3' : '','L4' : '','L5' : ''}
F112={'L1' : ' You are wise','L2' : 'beyond your','L3' : 'years.','L4' : '','L5' : ''}
F113={'L1' : ' A routine task','L2' : 'will turn into','L3' : 'an enchanting','L4' : 'adventure.','L5' : ''}
F114={'L1' : ' Beware of all','L2' : 'enterprises that','L3' : 'require new','L4' : 'clothes.','L5' : ''}
F115={'L1' : ' Be true to your','L2' : 'work, your word,','L3' : 'and your friend.','L4' : '','L5' : ''}
F116={'L1' : ' Goodness is the','L2' : 'only investment','L3' : 'that never','L4' : 'fails.','L5' : ''}
F117={'L1' : ' Forget','L2' : 'injuries; never','L3' : 'forget','L4' : 'kindnesses.','L5' : ''}
F118={'L1' : ' Respect','L2' : 'yourself and','L3' : 'others will','L4' : 'respect you.','L5' : ''}
F119={'L1' : ' A man cannot be','L2' : 'comfortable','L3' : 'without his own','L4' : 'approval.','L5' : ''}
F120={'L1' : ' It is easier to','L2' : 'stay out than to','L3' : 'get out.','L4' : '','L5' : ''}
F121={'L1' : ' Sing everyday','L2' : 'and chase the','L3' : 'mean blues away.','L4' : '','L5' : ''}
F122={'L1' : ' You will','L2' : 'receive money','L3' : 'from an','L4' : 'unexpected','L5' : 'source.'}
F123={'L1' : ' Attitude is a','L2' : 'little thing','L3' : 'that makes a big','L4' : 'difference.','L5' : ''}
F124={'L1' : ' Experience is','L2' : 'the best','L3' : 'teacher.','L4' : '','L5' : ''}
F125={'L1' : ' You will be','L2' : 'happy with your','L3' : 'spouse.','L4' : '','L5' : ''}
F126={'L1' : ' Expect the','L2' : 'unexpected.','L3' : '','L4' : '','L5' : ''}
F127={'L1' : ' Stay healthy.','L2' : 'Walk a mile.','L3' : '','L4' : '','L5' : ''}
F128={'L1' : ' The family that','L2' : 'plays together','L3' : 'stays together.','L4' : '','L5' : ''}
F129={'L1' : ' Eat chocolate','L2' : 'to have a','L3' : 'sweeter life.','L4' : '','L5' : ''}
F130={'L1' : ' Once you make a','L2' : 'decision the','L3' : 'universe','L4' : 'conspires to','L5' : 'make it happen.'}
F131={'L1' : ' Make yourself','L2' : 'necessary to','L3' : 'someone.','L4' : '','L5' : ''}
F132={'L1' : ' Nothing great','L2' : 'was ever','L3' : 'achieved without','L4' : 'enthusiasm.','L5' : ''}
F133={'L1' : ' Dance as if no','L2' : 'one is watching.','L3' : '','L4' : '','L5' : ''}
F134={'L1' : ' Live this day','L2' : 'as if it were','L3' : 'your last.','L4' : '','L5' : ''}
F135={'L1' : ' Reach for joy','L2' : 'and all else','L3' : 'will follow.','L4' : '','L5' : ''}
F136={'L1' : ' Move in the','L2' : 'direction of','L3' : 'your dreams.','L4' : '','L5' : ''}
F137={'L1' : ' Bloom where you','L2' : 'are planted.','L3' : '','L4' : '','L5' : ''}
F138={'L1' : ' Appreciate.','L2' : 'Appreciate.','L3' : 'Appreciate.','L4' : '','L5' : ''}
F139={'L1' : ' Happy news is','L2' : 'on its way.','L3' : '','L4' : '','L5' : ''}
F140={'L1' : ' Borrow money','L2' : 'from a','L3' : 'pessimist. They','L4' : 'dont expect it','L5' : 'back.'}
F141={'L1' : ' Life is what','L2' : 'happens to you','L3' : 'while you are','L4' : 'busy making','L5' : 'other plans.'}
F142={'L1' : ' Help! Im being','L2' : 'held prisoner in','L3' : 'a fortune cookie','L4' : 'factory.','L5' : ''}
F143={'L1' : ' Paradise is','L2' : 'always where','L3' : 'love dwells.','L4' : '','L5' : ''}
F144={'L1' : ' In dreams and','L2' : 'in love there','L3' : 'are no','L4' : 'impossibilities.','L5' : ''}
F145={'L1' : ' Love isnt','L2' : 'something you','L3' : 'find. Love is','L4' : 'something that','L5' : 'finds you.'}
F146={'L1' : ' Advice given to','L2' : 'you will be well','L3' : 'worth following.','L4' : '','L5' : ''}
F147={'L1' : ' It is a nice','L2' : 'day.','L3' : '','L4' : '','L5' : ''}
F148={'L1' : ' A wise man','L2' : 'knows','L3' : 'everything; a','L4' : 'shrewd one,','L5' : 'everybody.'}
F149={'L1' : ' When spider','L2' : 'webs unite, they','L3' : 'can tie up a','L4' : 'lion.','L5' : ''}
F150={'L1' : ' You will be the','L2' : 'sunshine in','L3' : 'someones life.','L4' : '','L5' : ''}
