F1={'L1' : ' Never give an','L2' : 'inch!','L3' : '','L4' : '','L5' : ''}
F2={'L1' : ' Reply hazy, ask','L2' : 'again later.','L3' : '','L4' : '','L5' : ''}
F3={'L1' : ' Snow Day --','L2' : 'stay home.','L3' : '','L4' : '','L5' : ''}
F4={'L1' : ' How unusual!','L2' : '','L3' : '','L4' : '','L5' : ''}
F5={'L1' : ' There will be','L2' : 'big changes for','L3' : 'you but you will','L4' : 'be happy.','L5' : ''}
F6={'L1' : ' Things will be','L2' : 'bright in P.M. A','L3' : 'cop will shine a','L4' : 'light in your','L5' : 'face.'}
F7={'L1' : ' Think twice','L2' : 'before speaking,','L3' : 'but dont say','L4' : 'think think','L5' : 'click click.'}
F8={'L1' : ' This will be a','L2' : 'memorable month','L3' : '-- no matter how','L4' : 'hard you try to','L5' : 'forget it.'}
F9={'L1' : ' Today is the','L2' : 'first day of the','L3' : 'rest of the','L4' : 'mess.','L5' : ''}
F10={'L1' : ' Today is the','L2' : 'tomorrow you','L3' : 'worried about','L4' : 'yesterday.','L5' : ''}
F11={'L1' : ' Tonights the','L2' : 'night: Sleep in','L3' : 'a eucalyptus','L4' : 'tree.','L5' : ''}
F12={'L1' : ' Try to get all','L2' : 'of your','L3' : 'posthumous','L4' : 'medals in','L5' : 'advance.'}
F13={'L1' : ' Try to relax','L2' : 'and enjoy the','L3' : 'crisis. --','L4' : 'Ashleigh','L5' : 'Brilliant'}
F14={'L1' : ' Tuesday After','L2' : 'Lunch is the','L3' : 'cosmic time of','L4' : 'the week.','L5' : ''}
F15={'L1' : ' Tuesday is the','L2' : 'Wednesday of the','L3' : 'rest of your','L4' : 'life.','L5' : ''}
F16={'L1' : ' You are as I am','L2' : 'with You.','L3' : '','L4' : '','L5' : ''}
F17={'L1' : ' You are deeply','L2' : 'attached to your','L3' : 'friends and','L4' : 'acquaintances.','L5' : ''}
F18={'L1' : ' You are number','L2' : '6! Who is number','L3' : 'one?','L4' : '','L5' : ''}
F19={'L1' : ' You are only','L2' : 'young once, but','L3' : 'you can stay','L4' : 'immature','L5' : 'indefinitely.'}
F20={'L1' : ' You have a','L2' : 'strong appeal','L3' : 'for members of','L4' : 'your own sex.','L5' : ''}
F21={'L1' : ' You have many','L2' : 'friends and very','L3' : 'few living','L4' : 'enemies.','L5' : ''}
F22={'L1' : ' You love your','L2' : 'home and want it','L3' : 'to be beautiful.','L4' : '','L5' : ''}
F23={'L1' : ' You may be gone','L2' : 'tomorrow, but','L3' : 'that doesnt mean','L4' : 'that you werent','L5' : 'here today.'}
F24={'L1' : ' You may get an','L2' : 'opportunity for','L3' : 'advancement','L4' : 'today. Watch it!','L5' : ''}
F25={'L1' : ' You','L2' : 'single-handedly','L3' : 'fought your way','L4' : 'into this','L5' : 'hopeless mess.'}
F26={'L1' : ' You will always','L2' : 'get the greatest','L3' : 'recognition for','L4' : 'the job you','L5' : 'least like.'}
F27={'L1' : ' You will be','L2' : 'misunderstood by','L3' : 'everyone.','L4' : '','L5' : ''}
F28={'L1' : ' You will be','L2' : 'recognized and','L3' : 'honored as a','L4' : 'community','L5' : 'leader.'}
F29={'L1' : ' You will be run','L2' : 'over by a bus.','L3' : '','L4' : '','L5' : ''}
F30={'L1' : ' You will be','L2' : 'singled out for','L3' : 'promotion in','L4' : 'your work.','L5' : ''}
F31={'L1' : ' You will be','L2' : 'surprised by a','L3' : 'loud noise.','L4' : '','L5' : ''}
F32={'L1' : ' You will gain','L2' : 'money by a','L3' : 'fattening','L4' : 'action.','L5' : ''}
F33={'L1' : ' You will have a','L2' : 'long and','L3' : 'unpleasant','L4' : 'discussion with','L5' : 'your supervisor.'}
F34={'L1' : ' You will live a','L2' : 'long, healthy,','L3' : 'happy life and','L4' : 'make bags of','L5' : 'money.'}
F35={'L1' : ' You will','L2' : 'outgrow your','L3' : 'usefulness.','L4' : '','L5' : ''}
F36={'L1' : ' You will pass','L2' : 'away very','L3' : 'quickly.','L4' : '','L5' : ''}
F37={'L1' : ' You will win','L2' : 'success in','L3' : 'whatever calling','L4' : 'you adopt.','L5' : ''}
F38={'L1' : ' You will wish','L2' : 'you hadnt.','L3' : '','L4' : '','L5' : ''}
F39={'L1' : ' Youll be','L2' : 'sorry...','L3' : '','L4' : '','L5' : ''}
F40={'L1' : ' Youll feel much','L2' : 'better once','L3' : 'youve given up','L4' : 'hope.','L5' : ''}
F41={'L1' : ' Youre being','L2' : 'followed. Cut','L3' : 'out the','L4' : 'hanky-panky for','L5' : 'a few days.'}
F42={'L1' : ' Your business','L2' : 'will go through','L3' : 'a period of','L4' : 'considerable','L5' : 'expansion.'}
F43={'L1' : ' Your fly might','L2' : 'be open (but','L3' : 'dont check it','L4' : 'just now).','L5' : ''}
F44={'L1' : ' Your ignorance','L2' : 'cramps my','L3' : 'conversation.','L4' : '','L5' : ''}
F45={'L1' : ' Your lucky','L2' : 'color has faded.','L3' : '','L4' : '','L5' : ''}
F46={'L1' : ' Your own','L2' : 'qualities will','L3' : 'help prevent','L4' : 'your advancement','L5' : 'in the world.'}
F47={'L1' : ' Some men dream','L2' : 'of fortunes,','L3' : 'others dream of','L4' : 'cookies.','L5' : ''}
F48={'L1' : ' You will be','L2' : 'hungry again in','L3' : 'one hour.','L4' : '','L5' : ''}
F49={'L1' : ' A starship ride','L2' : 'has been','L3' : 'promised to you','L4' : 'by the galactic','L5' : 'wizard.'}
F50={'L1' : ' A tub and a rub','L2' : 'will change your','L3' : 'day.','L4' : '','L5' : ''}
F51={'L1' : ' Because of your','L2' : 'melodic nature,','L3' : 'the moonlight','L4' : 'never misses an','L5' : 'appointment.'}
F52={'L1' : ' Confucius say','L2' : 'you have heart','L3' : 'as big as Texas.','L4' : '','L5' : ''}
F53={'L1' : ' Dont behave','L2' : 'with cold','L3' : 'manners.','L4' : '','L5' : ''}
F54={'L1' : ' Dont forget you','L2' : 'are always on','L3' : 'our minds.','L4' : '','L5' : ''}
F55={'L1' : ' Help! I am','L2' : 'being held','L3' : 'prisoner in a','L4' : 'Chinese bakery.','L5' : ''}
F56={'L1' : ' Its about time','L2' : 'I got out of','L3' : 'that cookie.','L4' : '','L5' : ''}
F57={'L1' : ' Never forget a','L2' : 'friend.','L3' : 'Especially if he','L4' : 'owes you.','L5' : ''}
F58={'L1' : ' Never wear your','L2' : 'best pants when','L3' : 'you go to fight','L4' : 'for freedom.','L5' : ''}
F59={'L1' : ' Someone will','L2' : 'invite you to a','L3' : 'Karaoke party.','L4' : '','L5' : ''}
F60={'L1' : ' Suppose you can','L2' : 'get what you','L3' : 'want.','L4' : '','L5' : ''}
F61={'L1' : ' That wasnt','L2' : 'chicken.','L3' : '','L4' : '','L5' : ''}
F62={'L1' : ' You will gain','L2' : 'admiration from','L3' : 'your peers.','L4' : '','L5' : ''}
F63={'L1' : ' You will','L2' : 'receive a','L3' : 'fortune cookie.','L4' : '','L5' : ''}
F64={'L1' : ' Accept that','L2' : 'some days youre','L3' : 'the pigeon, and','L4' : 'some days youre','L5' : 'the statue.'}
F65={'L1' : ' Always keep','L2' : 'your words soft','L3' : 'and sweet, just','L4' : 'in case you have','L5' : 'to eat them.'}
F66={'L1' : ' Decide that you','L2' : 'want it more','L3' : 'than you are','L4' : 'afraid of it. --','L5' : 'Bill Cosby'}
F67={'L1' : ' Dont fry bacon','L2' : 'in the nude.','L3' : '','L4' : '','L5' : ''}
F68={'L1' : ' Dont sweat the','L2' : 'petty things and','L3' : 'dont pet the','L4' : 'sweaty things.','L5' : '-- George Carlin'}
F69={'L1' : ' If opportunity','L2' : 'doesnt knock,','L3' : 'build a door. --','L4' : 'Milton Berle','L5' : ''}
F70={'L1' : ' When','L2' : 'everythings','L3' : 'coming your way,','L4' : 'youre in the','L5' : 'wrong lane.'}
F71={'L1' : ' Get your facts','L2' : 'first, and then','L3' : 'you can distort','L4' : 'them as much as','L5' : 'you please.'}
F72={'L1' : ' We are all born','L2' : 'ignorant, but','L3' : 'one must work','L4' : 'hard to remain','L5' : 'stupid.'}
F73={'L1' : ' Confidence is','L2' : 'the feeling you','L3' : 'have, before you','L4' : 'understand the','L5' : 'situation.'}
F74={'L1' : ' Adversity makes','L2' : 'men, and','L3' : 'prosperity makes','L4' : 'monsters.','L5' : ''}
F75={'L1' : ' A myth is a','L2' : 'religion, in','L3' : 'which no one any','L4' : 'longer believes.','L5' : ''}
F76={'L1' : ' There is never','L2' : 'enough time,','L3' : 'unless youre','L4' : 'serving it.','L5' : ''}
F77={'L1' : ' All growth','L2' : 'depends upon','L3' : 'activity.','L4' : '','L5' : ''}
F78={'L1' : ' You can tell','L2' : 'the ideals of a','L3' : 'nation, by its','L4' : 'advertisements.','L5' : ''}
F79={'L1' : ' Win new friends','L2' : 'but keep the','L3' : 'old. The first','L4' : 'are silver, the','L5' : 'latter gold.'}
F80={'L1' : ' Science is what','L2' : 'you know,','L3' : 'philosophy is','L4' : 'what you dont','L5' : 'know.'}
F81={'L1' : ' Nobody ever','L2' : 'forgets where he','L3' : 'buried the','L4' : 'hatchet.','L5' : ''}
F82={'L1' : ' The artist does','L2' : 'not see things','L3' : 'as they are, but','L4' : 'as he is.','L5' : ''}
F83={'L1' : ' War does not','L2' : 'determine who is','L3' : 'right - only who','L4' : 'is left.','L5' : ''}
F84={'L1' : ' Confidence is','L2' : 'the feeling you','L3' : 'have before you','L4' : 'understand the','L5' : 'situation.'}
F85={'L1' : ' Footprints on','L2' : 'the sands of','L3' : 'time are not','L4' : 'made by sitting','L5' : 'down.'}
F86={'L1' : ' The human body','L2' : 'is a peculiar','L3' : 'device, pat it','L4' : 'on the back and','L5' : 'the head swells.'}
F87={'L1' : ' He that waits','L2' : 'upon fortune, is','L3' : 'never sure of a','L4' : 'dinner.','L5' : ''}
F88={'L1' : ' Rust consumes','L2' : 'iron and envy','L3' : 'consumes itself.','L4' : '','L5' : ''}
F89={'L1' : ' Nothing is','L2' : 'impossible for','L3' : 'the man who','L4' : 'doesnt have to','L5' : 'do it himself.'}
F90={'L1' : ' Fame is the','L2' : 'perfume of','L3' : 'heroic deeds.','L4' : '','L5' : ''}
F91={'L1' : ' Laziness','L2' : 'travels so','L3' : 'slowly that','L4' : 'poverty soon','L5' : 'overtakes him.'}
F92={'L1' : ' Ambition is a','L2' : 'poor excuse for','L3' : 'not having sense','L4' : 'enough to be','L5' : 'lazy.'}
F93={'L1' : ' I have met the','L2' : 'enemy, and it is','L3' : 'the eyes of','L4' : 'other people.','L5' : ''}
F94={'L1' : ' The greatest','L2' : 'power is often','L3' : 'simple patience.','L4' : '','L5' : ''}
F95={'L1' : ' We may have all','L2' : 'come on','L3' : 'different ships,','L4' : 'but were in the','L5' : 'same boat now.'}
F96={'L1' : ' There is no','L2' : 'education like','L3' : 'adversity.','L4' : '','L5' : ''}
F97={'L1' : ' Too many church','L2' : 'services start','L3' : 'at eleven sharp','L4' : 'and end at','L5' : 'twelve dull.'}
F98={'L1' : ' They know','L2' : 'enough who know','L3' : 'how to learn.','L4' : '','L5' : ''}
F99={'L1' : ' An excuse is','L2' : 'worse than a','L3' : 'lie, for an','L4' : 'excuse is a lie,','L5' : 'guarded.'}
F100={'L1' : ' You have to','L2' : 'dream before','L3' : 'your dreams can','L4' : 'come true.','L5' : ''}
F101={'L1' : ' People are','L2' : 'always ready to','L3' : 'admit a mans','L4' : 'ability after he','L5' : 'gets there.'}
F102={'L1' : ' Be kind to','L2' : 'unkind people --','L3' : 'they need it the','L4' : 'most.','L5' : ''}
F103={'L1' : ' So rare is the','L2' : 'union of beauty','L3' : 'with modesty.','L4' : '','L5' : ''}
F104={'L1' : ' All things come','L2' : 'to him who goes','L3' : 'after them.','L4' : '','L5' : ''}
F105={'L1' : ' Like associates','L2' : 'with like.','L3' : '','L4' : '','L5' : ''}
F106={'L1' : ' It is not fair','L2' : 'to ask of others','L3' : 'what you are not','L4' : 'willing to do','L5' : 'yourself.'}
F107={'L1' : ' From our','L2' : 'ancestors come','L3' : 'our names from','L4' : 'our virtues our','L5' : 'honor.'}
F108={'L1' : ' Laugh and the','L2' : 'world laughs','L3' : 'with you, cry','L4' : 'and the world','L5' : 'laughs louder.'}
F109={'L1' : ' The hearing ear','L2' : 'is always found','L3' : 'close to the','L4' : 'speaking tongue.','L5' : ''}
F110={'L1' : ' Heroism feels,','L2' : 'and never','L3' : 'reasons, and is','L4' : 'therefore always','L5' : 'right.'}
F111={'L1' : ' Meeting people','L2' : 'formally, is','L3' : 'like viewing a','L4' : 'house without','L5' : 'going inside.'}
F112={'L1' : ' Use your time','L2' : 'well, if you','L3' : 'want to have','L4' : 'leisure time.','L5' : ''}
F113={'L1' : ' Acting is not','L2' : 'being emotional,','L3' : 'but being able','L4' : 'to express','L5' : 'emotion.'}
F114={'L1' : ' Some people','L2' : 'play very, very','L3' : 'well just so','L4' : 'they wont get','L5' : 'embarrassed.'}
F115={'L1' : ' The Extra Mile','L2' : 'will have no','L3' : 'traffic jams.','L4' : '','L5' : ''}
F116={'L1' : ' One who looks','L2' : 'for a friend','L3' : 'without faults','L4' : 'will have none.','L5' : ''}
F117={'L1' : ' The greatest','L2' : 'remedy for anger','L3' : 'is delay.','L4' : '','L5' : ''}
F118={'L1' : ' I became','L2' : 'insane, with','L3' : 'long intervals','L4' : 'of horrible','L5' : 'sanity.'}
F119={'L1' : ' Success comes','L2' : 'before work only','L3' : 'in the','L4' : 'dictionary.','L5' : ''}
F120={'L1' : ' We learn','L2' : 'geology the','L3' : 'morning after','L4' : 'the earthquake.','L5' : ''}
F121={'L1' : ' The next thing','L2' : 'to saying a good','L3' : 'thing yourself','L4' : 'is to quote one.','L5' : ''}
F122={'L1' : ' Pain is','L2' : 'inevitable.','L3' : 'Suffering is','L4' : 'optional.','L5' : ''}
F123={'L1' : ' Hope is a good','L2' : 'breakfast but a','L3' : 'bad supper.','L4' : '','L5' : ''}
F124={'L1' : ' Some luck lies','L2' : 'in not getting','L3' : 'what you thought','L4' : 'you wanted.','L5' : ''}
F125={'L1' : ' The penalty of','L2' : 'leadership is','L3' : 'loneliness.','L4' : '','L5' : ''}
F126={'L1' : ' Courage is the','L2' : 'art of being the','L3' : 'only one who','L4' : 'knows youre','L5' : 'scared to death.'}
F127={'L1' : ' A legend is an','L2' : 'old man with a','L3' : 'cane known for','L4' : 'what he used to','L5' : 'do.'}
F128={'L1' : ' In skating over','L2' : 'thin ice our','L3' : 'safety is in our','L4' : 'speed.','L5' : ''}
F129={'L1' : ' Money cant buy','L2' : 'you friends but','L3' : 'you do get a','L4' : 'better class of','L5' : 'enemies.'}
F130={'L1' : ' Everybody is','L2' : 'ignorant -- only','L3' : 'on different','L4' : 'subjects.','L5' : ''}
F131={'L1' : ' We have met the','L2' : 'enemy and he is','L3' : 'us.','L4' : '','L5' : ''}
F132={'L1' : ' Most people','L2' : 'fail in life','L3' : 'because they','L4' : 'major in minor','L5' : 'things.'}
F133={'L1' : ' Honesty is as','L2' : 'rare as a man','L3' : 'without','L4' : 'self-pity.','L5' : ''}
F134={'L1' : ' The best mirror','L2' : 'is an old','L3' : 'friend.','L4' : '','L5' : ''}
F135={'L1' : ' Pleasure can be','L2' : 'supported by an','L3' : 'illusion, but','L4' : 'happiness rests','L5' : 'upon truth.'}
F136={'L1' : ' Many men die at','L2' : '25 and arent','L3' : 'buried until','L4' : 'they are 75.','L5' : ''}
F137={'L1' : ' Hollywood is a','L2' : 'place where','L3' : 'people from Iowa','L4' : 'mistake each','L5' : 'other for stars.'}
F138={'L1' : ' It is in the','L2' : 'treatment of','L3' : 'trifles that a','L4' : 'person shows','L5' : 'what they are.'}
F139={'L1' : ' Anyone who','L2' : 'thinks the sky','L3' : 'is the limit,','L4' : 'has limited','L5' : 'imagination.'}
F140={'L1' : ' Never confuse','L2' : 'motion with','L3' : 'action.','L4' : '','L5' : ''}
F141={'L1' : ' Nothing','L2' : 'astonishes men','L3' : 'so much as','L4' : 'common sense and','L5' : 'plain dealing.'}
F142={'L1' : ' Everything has','L2' : 'been figured','L3' : 'out, except how','L4' : 'to live.','L5' : ''}
F143={'L1' : ' When you come','L2' : 'to a roadblock,','L3' : 'take a detour.','L4' : '','L5' : ''}
F144={'L1' : ' People give us','L2' : 'credit only for','L3' : 'what we','L4' : 'ourselves','L5' : 'believe.'}
F145={'L1' : ' Sympathy is a','L2' : 'virtue unknown','L3' : 'in nature.','L4' : '','L5' : ''}
F146={'L1' : ' The Green Bay','L2' : 'Packers never','L3' : 'lost a football','L4' : 'game. They just','L5' : 'ran out of time.'}
F147={'L1' : ' Conscience is','L2' : 'the sentinel of','L3' : 'virtue.','L4' : '','L5' : ''}
F148={'L1' : ' A ruffled mind','L2' : 'makes a restless','L3' : 'pillow.','L4' : '','L5' : ''}
F149={'L1' : ' There is no','L2' : 'sanctuary of','L3' : 'virtue like','L4' : 'home.','L5' : ''}
F150={'L1' : ' Gratitude is','L2' : 'the fairest','L3' : 'blossom which','L4' : 'springs from the','L5' : 'soul.'}
