F1={'L1' : ' Believing is','L2' : 'doing.','L3' : '','L4' : '','L5' : ''}
F2={'L1' : ' Your dynamic','L2' : 'eyes have','L3' : 'attracted a','L4' : 'secret admirer.','L5' : ''}
F3={'L1' : ' You know where','L2' : 'you are going','L3' : 'and how to get','L4' : 'there.','L5' : ''}
F4={'L1' : ' Go confidently','L2' : 'in the direction','L3' : 'of your dreams.','L4' : '','L5' : ''}
F5={'L1' : ' Your ability to','L2' : 'pick a winner','L3' : 'will bring you','L4' : 'success.','L5' : ''}
F6={'L1' : ' Humor usually','L2' : 'works at the','L3' : 'moment of','L4' : 'awkwardness.','L5' : ''}
F7={'L1' : ' Stop','L2' : 'procrastinating','L3' : '- starting','L4' : 'tomorrow.','L5' : ''}
F8={'L1' : ' Enthusiastic','L2' : 'leadership gets','L3' : 'you a promotion','L4' : 'when you least','L5' : 'expect it.'}
F9={'L1' : ' You love','L2' : 'Chinese food.','L3' : '','L4' : '','L5' : ''}
F10={'L1' : ' You are far','L2' : 'more influential','L3' : 'than you think.','L4' : '','L5' : ''}
F11={'L1' : ' Adjust','L2' : 'finances, make','L3' : 'budgets, to','L4' : 'improve your','L5' : 'standing.'}
F12={'L1' : ' Happiness is','L2' : 'not the absence','L3' : 'of conflict, but','L4' : 'the ability to','L5' : 'cope with it.'}
F13={'L1' : ' Your co-workers','L2' : 'take pleasure in','L3' : 'your great sense','L4' : 'of creativity.','L5' : ''}
F14={'L1' : ' You are one of','L2' : 'the people who','L3' : 'goes places in','L4' : 'life.','L5' : ''}
F15={'L1' : ' Others enjoy','L2' : 'your company.','L3' : '','L4' : '','L5' : ''}
F16={'L1' : ' When in doubt,','L2' : 'let your','L3' : 'instincts guide','L4' : 'you.','L5' : ''}
F17={'L1' : ' A cheerful','L2' : 'message is on','L3' : 'its way to you.','L4' : '','L5' : ''}
F18={'L1' : ' A pleasant','L2' : 'surprise is in','L3' : 'store for you','L4' : 'tonight.','L5' : ''}
F19={'L1' : ' To courageously','L2' : 'shoulder the','L3' : 'responsibility','L4' : 'of ones mistake','L5' : 'is character.'}
F20={'L1' : ' The joyful','L2' : 'energy of the','L3' : 'day will have a','L4' : 'positive affect','L5' : 'on you.'}
F21={'L1' : ' Dogs have','L2' : 'owners, cats','L3' : 'have staff.','L4' : '','L5' : ''}
F22={'L1' : ' Be patient; in','L2' : 'time, even an','L3' : 'egg will walk.','L4' : '','L5' : ''}
F23={'L1' : ' You are not a','L2' : 'person who can','L3' : 'be ignored.','L4' : '','L5' : ''}
F24={'L1' : ' You always know','L2' : 'the right times','L3' : 'to be assertive','L4' : 'or to simply','L5' : 'wait.'}
F25={'L1' : ' Reading to the','L2' : 'mind is what','L3' : 'exercise is to','L4' : 'the body.','L5' : ''}
F26={'L1' : ' Eat something','L2' : 'you never tried','L3' : 'before.','L4' : '','L5' : ''}
F27={'L1' : ' Your life','L2' : 'becomes more and','L3' : 'more of an','L4' : 'adventure!','L5' : ''}
F28={'L1' : ' You need to','L2' : 'live','L3' : 'authentically,','L4' : 'and you cant','L5' : 'ignore that.'}
F29={'L1' : ' Make all you','L2' : 'can, save all','L3' : 'you can, give','L4' : 'all you can.','L5' : ''}
F30={'L1' : ' A well-aimed','L2' : 'spear is worth','L3' : 'three.','L4' : '','L5' : ''}
F31={'L1' : ' To build a','L2' : 'better world,','L3' : 'start in your','L4' : 'community.','L5' : ''}
F32={'L1' : ' May you have','L2' : 'great luck.','L3' : '','L4' : '','L5' : ''}
F33={'L1' : ' A kind word','L2' : 'will keep','L3' : 'someone warm for','L4' : 'years.','L5' : ''}
F34={'L1' : ' Nothing in the','L2' : 'world is','L3' : 'accomplished','L4' : 'without passion.','L5' : ''}
F35={'L1' : ' Human invented','L2' : 'language to','L3' : 'satisfy the need','L4' : 'to complain.','L5' : ''}
F36={'L1' : ' Accept what','L2' : 'comes to you','L3' : 'each day.','L4' : '','L5' : ''}
F37={'L1' : ' A small lucky','L2' : 'package is on','L3' : 'its way to you','L4' : 'soon.','L5' : ''}
F38={'L1' : ' In human','L2' : 'endeavor, chance','L3' : 'favors the','L4' : 'prepared mind.','L5' : ''}
F39={'L1' : ' Do not upset','L2' : 'the penguin','L3' : 'today.','L4' : '','L5' : ''}
F40={'L1' : ' Dont cry.','L2' : '','L3' : '','L4' : '','L5' : ''}
F41={'L1' : ' The best way to','L2' : 'give credit is','L3' : 'to give it away.','L4' : '','L5' : ''}
F42={'L1' : ' Grant yourself','L2' : 'a wish this','L3' : 'year; only you','L4' : 'can do it.','L5' : ''}
F43={'L1' : ' Love thy','L2' : 'neighbor; just','L3' : 'dont get caught.','L4' : '','L5' : ''}
F44={'L1' : ' You will be','L2' : 'selected for a','L3' : 'promotion','L4' : 'because of your','L5' : 'accomplishments.'}
F45={'L1' : ' You will','L2' : 'receive a gift','L3' : 'from someone','L4' : 'that cares about','L5' : 'you.'}
F46={'L1' : ' You are not','L2' : 'illiterate.','L3' : '','L4' : '','L5' : ''}
F47={'L1' : ' Love because it','L2' : 'is the only true','L3' : 'adventure.','L4' : '','L5' : ''}
F48={'L1' : ' Treasure what','L2' : 'you have.','L3' : '','L4' : '','L5' : ''}
F49={'L1' : ' The greatest','L2' : 'precept is','L3' : 'continual','L4' : 'awareness.','L5' : ''}
F50={'L1' : ' A new friend','L2' : 'helps you break','L3' : 'out of an old','L4' : 'routine.','L5' : ''}
F51={'L1' : ' I have a','L2' : 'dream...Time to','L3' : 'go to bed.','L4' : '','L5' : ''}
F52={'L1' : ' Your skill will','L2' : 'accomplish what','L3' : 'the force of','L4' : 'many cannot.','L5' : ''}
F53={'L1' : ' You will soon','L2' : 'be surrounded by','L3' : 'good friends and','L4' : 'laughter.','L5' : ''}
F54={'L1' : ' The best is yet','L2' : 'to come.','L3' : '','L4' : '','L5' : ''}
F55={'L1' : ' It is better to','L2' : 'be the hammer','L3' : 'than the anvil.','L4' : '','L5' : ''}
F56={'L1' : ' He who climbs a','L2' : 'ladder must','L3' : 'begin at the','L4' : 'first step.','L5' : ''}
F57={'L1' : ' Action speaks','L2' : 'nothing, without','L3' : 'the motive.','L4' : '','L5' : ''}
F58={'L1' : ' Give yourself','L2' : 'some peace and','L3' : 'quiet for at','L4' : 'least a few','L5' : 'hours.'}
F59={'L1' : ' Live each day','L2' : 'well and wisely.','L3' : '','L4' : '','L5' : ''}
F60={'L1' : ' Old dreams','L2' : 'never die they','L3' : 'just get filed','L4' : 'away.','L5' : ''}
F61={'L1' : ' You can fix it','L2' : 'with a little','L3' : 'extra energy and','L4' : 'a positive','L5' : 'attitude.'}
F62={'L1' : ' Life is a verb.','L2' : '','L3' : '','L4' : '','L5' : ''}
F63={'L1' : ' Many folks are','L2' : 'about as happy','L3' : 'as they make up','L4' : 'their minds to','L5' : 'be.'}
F64={'L1' : ' Its kind of fun','L2' : 'to do the','L3' : 'impossible.','L4' : '','L5' : ''}
F65={'L1' : ' Wow! A secret','L2' : 'message from','L3' : 'your teeth!','L4' : '','L5' : ''}
F66={'L1' : ' You should be','L2' : 'able to make','L3' : 'money and hold','L4' : 'on to it.','L5' : ''}
F67={'L1' : ' You have a','L2' : 'curious smile','L3' : 'and a mysterious','L4' : 'nature.','L5' : ''}
F68={'L1' : ' Your success','L2' : 'will astonish','L3' : 'everyone.','L4' : '','L5' : ''}
F69={'L1' : ' It is better to','L2' : 'have a hen','L3' : 'tomorrow than an','L4' : 'egg today.','L5' : ''}
F70={'L1' : ' Judge each day','L2' : 'not by the','L3' : 'harvest you reap','L4' : 'but by the seeds','L5' : 'you plant.'}
F71={'L1' : ' Your hard work','L2' : 'will get payoff','L3' : 'today.','L4' : '','L5' : ''}
F72={'L1' : ' Today is the','L2' : 'tomorrow we','L3' : 'worried about','L4' : 'yesterday.','L5' : ''}
F73={'L1' : ' There are no','L2' : 'shortcuts to any','L3' : 'place worth','L4' : 'going.','L5' : ''}
F74={'L1' : ' No matter what','L2' : 'your past has','L3' : 'been, you have a','L4' : 'spotless future.','L5' : ''}
F75={'L1' : ' Your secret','L2' : 'desire to','L3' : 'completely','L4' : 'change your life','L5' : 'will manifest.'}
F76={'L1' : ' Soon you will','L2' : 'be sitting on','L3' : 'top of the','L4' : 'world.','L5' : ''}
F77={'L1' : ' You are never','L2' : 'selfish with','L3' : 'your advice or','L4' : 'your help.','L5' : ''}
F78={'L1' : ' A thrilling','L2' : 'time is in store','L3' : 'for you.','L4' : '','L5' : ''}
F79={'L1' : ' Its tough to be','L2' : 'fascinating.','L3' : '','L4' : '','L5' : ''}
F80={'L1' : ' Soon life will','L2' : 'become more','L3' : 'interesting.','L4' : '','L5' : ''}
F81={'L1' : ' Luck sometimes','L2' : 'visits a fool,','L3' : 'but it never','L4' : 'sits down with','L5' : 'him.'}
F82={'L1' : ' Arent you glad','L2' : 'you just had a','L3' : 'great meal?','L4' : '','L5' : ''}
F83={'L1' : ' Only talented','L2' : 'people get help','L3' : 'from others.','L4' : '','L5' : ''}
F84={'L1' : ' You will be','L2' : 'successful in','L3' : 'your work.','L4' : '','L5' : ''}
F85={'L1' : ' You will spend','L2' : 'old age in','L3' : 'comfort and','L4' : 'material wealth.','L5' : ''}
F86={'L1' : ' You are','L2' : 'vigorous in','L3' : 'words and','L4' : 'action.','L5' : ''}
F87={'L1' : ' The one who','L2' : 'snores will','L3' : 'always fall','L4' : 'asleep first.','L5' : ''}
F88={'L1' : ' An alien of','L2' : 'some sort will','L3' : 'be appearing to','L4' : 'you shortly!','L5' : ''}
F89={'L1' : ' Rest is a good','L2' : 'thing, but','L3' : 'boredom is its','L4' : 'brother.','L5' : ''}
F90={'L1' : ' Think of how','L2' : 'you can assist','L3' : 'on a problem,','L4' : 'not whom to','L5' : 'blame.'}
F91={'L1' : ' Take it easy.','L2' : '','L3' : '','L4' : '','L5' : ''}
F92={'L1' : ' Trust your','L2' : 'intuition. The','L3' : 'universe is','L4' : 'guiding your','L5' : 'life.'}
F93={'L1' : ' Use your head,','L2' : 'but live in your','L3' : 'heart.','L4' : '','L5' : ''}
F94={'L1' : ' Dont find','L2' : 'fault, find a','L3' : 'remedy.','L4' : '','L5' : ''}
F95={'L1' : ' It may be those','L2' : 'who do most,','L3' : 'dream most.','L4' : '','L5' : ''}
F96={'L1' : ' Your passions','L2' : 'sweep you away.','L3' : '','L4' : '','L5' : ''}
F97={'L1' : ' Listen to','L2' : 'yourself more','L3' : 'often.','L4' : '','L5' : ''}
F98={'L1' : ' Think of','L2' : 'mothers','L3' : 'exhortations','L4' : 'more.','L5' : ''}
F99={'L1' : ' The gambler is','L2' : 'like the','L3' : 'fisherman; both','L4' : 'have beginners','L5' : 'luck.'}
F100={'L1' : ' You are given','L2' : 'the chance to','L3' : 'take part in an','L4' : 'exciting','L5' : 'adventure.'}
F101={'L1' : ' The simplest','L2' : 'answer is to','L3' : 'act.','L4' : '','L5' : ''}
F102={'L1' : ' Keep your feet','L2' : 'on the ground','L3' : 'even though','L4' : 'friends flatter','L5' : 'you.'}
F103={'L1' : ' You are the man','L2' : 'of righteousness','L3' : 'and integrity.','L4' : '','L5' : ''}
F104={'L1' : ' He who seeks','L2' : 'will find.','L3' : '','L4' : '','L5' : ''}
F105={'L1' : ' The smart thing','L2' : 'to do is to','L3' : 'begin trusting','L4' : 'your intuitions.','L5' : ''}
F106={'L1' : ' Your many','L2' : 'hidden talents','L3' : 'will become','L4' : 'obvious to those','L5' : 'around you.'}
F107={'L1' : ' Pick a path','L2' : 'with heart.','L3' : '','L4' : '','L5' : ''}
F108={'L1' : ' It takes more','L2' : 'than good memory','L3' : 'to have good','L4' : 'memories.','L5' : ''}
F109={'L1' : ' Face facts with','L2' : 'dignity.','L3' : '','L4' : '','L5' : ''}
F110={'L1' : ' Be calm when','L2' : 'confronting an','L3' : 'emergency','L4' : 'crisis.','L5' : ''}
F111={'L1' : ' Do you believe?','L2' : 'Endurance and','L3' : 'persistence will','L4' : 'be rewarded.','L5' : ''}
F112={'L1' : ' A new wardrobe','L2' : 'brings great joy','L3' : 'and change in','L4' : 'your life.','L5' : ''}
F113={'L1' : ' Everyone agrees','L2' : 'you are the','L3' : 'best.','L4' : '','L5' : ''}
F114={'L1' : ' Everything will','L2' : 'now come your','L3' : 'way.','L4' : '','L5' : ''}
F115={'L1' : ' You will be','L2' : 'called to fill a','L3' : 'position of high','L4' : 'honor and','L5' : 'responsibility.'}
F116={'L1' : ' The eyes','L2' : 'believe','L3' : 'themselves; the','L4' : 'ears believe','L5' : 'other people.'}
F117={'L1' : ' Good beginning','L2' : 'is half done.','L3' : '','L4' : '','L5' : ''}
F118={'L1' : ' Its the worst','L2' : 'of times, you','L3' : 'need to summon','L4' : 'your optimism.','L5' : ''}
F119={'L1' : ' You are','L2' : 'cautious in','L3' : 'showing your','L4' : 'true self to','L5' : 'others.'}
F120={'L1' : ' Your ability to','L2' : 'accomplish tasks','L3' : 'will follow with','L4' : 'success.','L5' : ''}
F121={'L1' : ' We all have','L2' : 'extraordinary','L3' : 'coded within us,','L4' : 'waiting to be','L5' : 'released.'}
F122={'L1' : ' Compassion is a','L2' : 'way of being.','L3' : '','L4' : '','L5' : ''}
F123={'L1' : ' You will always','L2' : 'have good luck','L3' : 'in your personal','L4' : 'affairs.','L5' : ''}
F124={'L1' : ' The pleasure of','L2' : 'what we enjoy is','L3' : 'lost by wanting','L4' : 'more.','L5' : ''}
F125={'L1' : ' Did you','L2' : 'remember to','L3' : 'order your','L4' : 'takeout also?','L5' : ''}
F126={'L1' : ' Perhaps youve','L2' : 'been focusing','L3' : 'too much on that','L4' : 'one thing.','L5' : ''}
F127={'L1' : ' Right now','L2' : 'theres an energy','L3' : 'pushing you in a','L4' : 'new direction.','L5' : ''}
F128={'L1' : ' Everybody feels','L2' : 'lucky for having','L3' : 'you as a friend.','L4' : '','L5' : ''}
F129={'L1' : ' When the moment','L2' : 'comes, take the','L3' : 'top one.','L4' : '','L5' : ''}
F130={'L1' : ' Sometimes','L2' : 'traveling to new','L3' : 'places leads to','L4' : 'great','L5' : 'transformation.'}
F131={'L1' : ' There is always','L2' : 'a way&mdash;if','L3' : 'you are','L4' : 'committed.','L5' : ''}
F132={'L1' : ' Life is too','L2' : 'short to waste','L3' : 'time hating','L4' : 'anyone.','L5' : ''}
F133={'L1' : ' Dont just spend','L2' : 'time, invest it.','L3' : '','L4' : '','L5' : ''}
F134={'L1' : ' Life always','L2' : 'gets harder near','L3' : 'the summit.','L4' : '','L5' : ''}
F135={'L1' : ' Take the chance','L2' : 'while you still','L3' : 'have the choice.','L4' : '','L5' : ''}
F136={'L1' : ' It is much','L2' : 'easier to be','L3' : 'critical than to','L4' : 'be correct.','L5' : ''}
F137={'L1' : ' Enjoy life! It','L2' : 'is better to be','L3' : 'happy than wise.','L4' : '','L5' : ''}
F138={'L1' : ' To make the','L2' : 'cart go, you','L3' : 'must grease the','L4' : 'wheels.','L5' : ''}
F139={'L1' : ' You are','L2' : 'contemplating','L3' : 'some action','L4' : 'which will bring','L5' : 'credit upon you.'}
F140={'L1' : ' You may be','L2' : 'disappointed if','L3' : 'you fail, but','L4' : 'you are doomed','L5' : 'if you dont try.'}
F141={'L1' : ' You will always','L2' : 'get what you','L3' : 'want through','L4' : 'your charm and','L5' : 'personality.'}
F142={'L1' : ' The big issues','L2' : 'are work,','L3' : 'career, or','L4' : 'status right','L5' : 'now.'}
F143={'L1' : ' Your emotional','L2' : 'currents are','L3' : 'flowing','L4' : 'powerfully now.','L5' : ''}
F144={'L1' : ' Any decision','L2' : 'you have to make','L3' : 'tomorrow is a','L4' : 'good decision.','L5' : ''}
F145={'L1' : ' Consume less.','L2' : 'Share more.','L3' : 'Enjoy life.','L4' : '','L5' : ''}
F146={'L1' : ' The secret of','L2' : 'staying young is','L3' : 'good health and','L4' : 'lying about your','L5' : 'age.'}
F147={'L1' : ' Spring has','L2' : 'sprung. Life is','L3' : 'blooming.','L4' : '','L5' : ''}
F148={'L1' : ' Go ask your','L2' : 'mom.','L3' : '','L4' : '','L5' : ''}
F149={'L1' : ' The possibility','L2' : 'of a career','L3' : 'change is near.','L4' : '','L5' : ''}
F150={'L1' : ' The important','L2' : 'thing is to','L3' : 'never stop','L4' : 'questioning.','L5' : ''}
