F1={'L1' : ' Someone will','L2' : 'look to you for','L3' : 'help and advice.','L4' : '','L5' : ''}
F2={'L1' : ' Something truly','L2' : 'delightful','L3' : 'awaits you.','L4' : '','L5' : ''}
F3={'L1' : ' Soon a stranger','L2' : 'shall enlighten','L3' : 'you.','L4' : '','L5' : ''}
F4={'L1' : ' Soon you will','L2' : 'encounter a','L3' : 'whole new world','L4' : 'of opportunity.','L5' : ''}
F5={'L1' : ' Speed is no','L2' : 'substitute for','L3' : 'accuracy.','L4' : '','L5' : ''}
F6={'L1' : ' Step by step','L2' : 'you will ascend','L3' : 'the staircase to','L4' : 'success','L5' : ''}
F7={'L1' : ' Stick to one','L2' : 'thing, and all','L3' : 'will come.','L4' : '','L5' : ''}
F8={'L1' : ' Striving for','L2' : 'the best will','L3' : 'bring you the','L4' : 'best.','L5' : ''}
F9={'L1' : ' Success is a','L2' : 'sure thing.','L3' : '','L4' : '','L5' : ''}
F10={'L1' : ' Success is','L2' : 'yours if you','L3' : 'continue on the','L4' : 'path you have','L5' : 'chosen.'}
F11={'L1' : ' Take a break','L2' : 'from your usual','L3' : 'routine & enjoy','L4' : 'yourself.','L5' : ''}
F12={'L1' : ' Take charge of','L2' : 'your own life','L3' : 'and decisions.','L4' : '','L5' : ''}
F13={'L1' : ' Take pains to','L2' : 'prevent getting','L3' : 'completely','L4' : 'exhausted.','L5' : ''}
F14={'L1' : ' Take steps now','L2' : 'to ensure','L3' : 'success.','L4' : '','L5' : ''}
F15={'L1' : ' Tasks where','L2' : 'skill is','L3' : 'essential may be','L4' : 'accomplished.','L5' : ''}
F16={'L1' : ' That','L2' : 'long-sought','L3' : 'opportunity will','L4' : 'soon arise.','L5' : ''}
F17={'L1' : ' The answer to','L2' : 'your problem','L3' : 'will soon be','L4' : 'obvious to you.','L5' : ''}
F18={'L1' : ' The art of','L2' : 'keeping secrets','L3' : 'will be your key','L4' : 'to success.','L5' : ''}
F19={'L1' : ' The beginning','L2' : 'of wisdom is to','L3' : 'desire it.','L4' : '','L5' : ''}
F20={'L1' : ' The cautious','L2' : 'seldom make','L3' : 'mistakes.','L4' : '','L5' : ''}
F21={'L1' : ' The colour red','L2' : 'will be','L3' : 'important to','L4' : 'you.','L5' : ''}
F22={'L1' : ' The current','L2' : 'year will bring','L3' : 'you great/much','L4' : 'happiness.','L5' : ''}
F23={'L1' : ' The evening','L2' : 'promises','L3' : 'romantic','L4' : 'interests.','L5' : ''}
F24={'L1' : ' The full moon','L2' : 'sees an increase','L3' : 'in status or','L4' : 'income.','L5' : ''}
F25={'L1' : ' The glitter of','L2' : 'gold will','L3' : 'brighten your','L4' : 'skies.','L5' : ''}
F26={'L1' : ' The joys of','L2' : 'leisure time','L3' : 'will be yours.','L4' : '','L5' : ''}
F27={'L1' : ' The last wish','L2' : 'you made will','L3' : 'come true.','L4' : '','L5' : ''}
F28={'L1' : ' The longest','L2' : 'journey is','L3' : 'started by a','L4' : 'single step;','L5' : 'take it.'}
F29={'L1' : ' The new moon','L2' : 'will bring','L3' : 'pleasant','L4' : 'surprises.','L5' : ''}
F30={'L1' : ' The project','L2' : 'that you have in','L3' : 'mind now gains','L4' : 'momentum.','L5' : ''}
F31={'L1' : ' The rainbow','L2' : 'treasures will','L3' : 'soon belong to','L4' : 'you.','L5' : ''}
F32={'L1' : ' The respect &','L2' : 'help of','L3' : 'influential','L4' : 'people will soon','L5' : 'be yours.'}
F33={'L1' : ' The skys the','L2' : 'limit this','L3' : 'month.','L4' : '','L5' : ''}
F34={'L1' : ' The social','L2' : 'scene will be a','L3' : 'lot more fun','L4' : 'today.','L5' : ''}
F35={'L1' : ' The star of','L2' : 'riches is','L3' : 'shining on you.','L4' : '','L5' : ''}
F36={'L1' : ' The strengths','L2' : 'in your','L3' : 'character will','L4' : 'bring you','L5' : 'serenity.'}
F37={'L1' : ' The tide of','L2' : 'change','L3' : 'approaches.','L4' : '','L5' : ''}
F38={'L1' : ' The time is','L2' : 'suitable for','L3' : 'long-range plans','L4' : 'and goals.','L5' : ''}
F39={'L1' : ' The weekend','L2' : 'ahead predicts','L3' : 'enjoyment.','L4' : '','L5' : ''}
F40={'L1' : ' The wisdom of','L2' : 'knowing when to','L3' : 'speak will bring','L4' : 'you respect.','L5' : ''}
F41={'L1' : ' The world will','L2' : 'soon be ready to','L3' : 'receive your','L4' : 'talent.','L5' : ''}
F42={'L1' : ' There are good','L2' : 'times ahead for','L3' : 'you.','L4' : '','L5' : ''}
F43={'L1' : ' There is a','L2' : 'tendency to','L3' : 'carry activities','L4' : 'too far.','L5' : ''}
F44={'L1' : ' There is new','L2' : 'hope for','L3' : 'projects you had','L4' : 'almost given up','L5' : 'on.'}
F45={'L1' : ' There will be a','L2' : 'change in plans','L3' : 'this weekend.','L4' : '','L5' : ''}
F46={'L1' : ' This is a good','L2' : 'day to get','L3' : 'things done that','L4' : 'require','L5' : 'expertise.'}
F47={'L1' : ' This is a good','L2' : 'time to finish','L3' : 'up old tasks.','L4' : '','L5' : ''}
F48={'L1' : ' This is a month','L2' : 'of','L3' : 'opportunities,','L4' : 'but you must','L5' : 'stay alert.'}
F49={'L1' : ' This is the','L2' : 'perfect weekend','L3' : 'to break','L4' : 'routine.','L5' : ''}
F50={'L1' : ' This time is','L2' : 'suitable for','L3' : 'long-range plans','L4' : 'and goals.','L5' : ''}
F51={'L1' : ' To get what you','L2' : 'want, you must','L3' : 'commit yourself','L4' : 'for some time.','L5' : ''}
F52={'L1' : ' To reach','L2' : 'distant places,','L3' : 'one has to take','L4' : 'the first step.','L5' : ''}
F53={'L1' : ' Today is a','L2' : 'lucky day for','L3' : 'those who remain','L4' : 'cheerful and','L5' : 'optimistic.'}
F54={'L1' : ' Today will be','L2' : 'lucky and','L3' : 'memorable for','L4' : 'you.','L5' : ''}
F55={'L1' : ' Traveling down','L2' : 'south will lead','L3' : 'you to','L4' : 'unexpected','L5' : 'happiness.'}
F56={'L1' : ' Trust him, but','L2' : 'still keep your','L3' : 'eyes open.','L4' : '','L5' : ''}
F57={'L1' : ' Try to resolve','L2' : 'contradictory','L3' : 'issues with','L4' : 'reason.','L5' : ''}
F58={'L1' : ' Tuesday is an','L2' : 'especially','L3' : 'important day','L4' : 'for you.','L5' : ''}
F59={'L1' : ' Tuesdays &','L2' : 'Thursdays stack','L3' : 'odds in your','L4' : 'favour.','L5' : ''}
F60={'L1' : ' Unplanned','L2' : 'activities will','L3' : 'be the most','L4' : 'satisfying.','L5' : ''}
F61={'L1' : ' Use your','L2' : 'ingenuity for','L3' : 'unqualified','L4' : 'success.','L5' : ''}
F62={'L1' : ' Utilize your','L2' : 'talent for','L3' : 'getting things','L4' : 'organized.','L5' : ''}
F63={'L1' : ' Valuable','L2' : 'information will','L3' : 'be supplied by a','L4' : 'child.','L5' : ''}
F64={'L1' : ' Wednesday is','L2' : 'the day to make','L3' : 'your move.','L4' : '','L5' : ''}
F65={'L1' : ' Welcome','L2' : 'affectionate','L3' : 'gestures from','L4' : 'friends or','L5' : 'lovers.'}
F66={'L1' : ' When the','L2' : 'daffodils bloom,','L3' : 'so will great','L4' : 'joy in your','L5' : 'life.'}
F67={'L1' : ' When time','L2' : 'permits, your','L3' : 'personal life','L4' : 'will be','L5' : 'exciting.'}
F68={'L1' : ' When winter','L2' : 'comes, heaven','L3' : 'will rain','L4' : 'success on you.','L5' : ''}
F69={'L1' : ' With renewed','L2' : 'energy,','L3' : 'accomplish what','L4' : 'you can.','L5' : ''}
F70={'L1' : ' You always know','L2' : 'when to be kind','L3' : 'and when to be','L4' : 'assertive.','L5' : ''}
F71={'L1' : ' You and your','L2' : 'loved ones will','L3' : 'be happy in your','L4' : 'life together.','L5' : ''}
F72={'L1' : ' You and your','L2' : 'partner will be','L3' : 'happy in your','L4' : 'life together.','L5' : ''}
F73={'L1' : ' You are a','L2' : 'bundle of','L3' : 'energy, always','L4' : 'on the go.','L5' : ''}
F74={'L1' : ' You are a','L2' : 'person of','L3' : 'culture.','L4' : '','L5' : ''}
F75={'L1' : ' You are a','L2' : 'practical person','L3' : 'with both feet','L4' : 'on the ground.','L5' : ''}
F76={'L1' : ' You are about','L2' : 'to make a most','L3' : 'valuable','L4' : 'discovery.','L5' : ''}
F77={'L1' : ' You are deeply','L2' : 'attached to your','L3' : 'family and home.','L4' : '','L5' : ''}
F78={'L1' : ' You are','L2' : 'extremely','L3' : 'generous and','L4' : 'always thinking','L5' : 'of others.'}
F79={'L1' : ' You are heading','L2' : 'for a land of','L3' : 'sunshine and','L4' : 'fun.','L5' : ''}
F80={'L1' : ' You are heading','L2' : 'in the right','L3' : 'direction.','L4' : '','L5' : ''}
F81={'L1' : ' You are kind','L2' : 'and trustworthy','L3' : 'by nature.','L4' : '','L5' : ''}
F82={'L1' : ' You are','L2' : 'mentally alert.','L3' : 'Put your mind to','L4' : 'good use.','L5' : ''}
F83={'L1' : ' You are next in','L2' : 'line for','L3' : 'promotion.','L4' : '','L5' : ''}
F84={'L1' : ' You are no','L2' : 'doubt obligated','L3' : 'to do the proper','L4' : 'thing.','L5' : ''}
F85={'L1' : ' You are one of','L2' : 'the people who','L3' : 'will go places.','L4' : '','L5' : ''}
F86={'L1' : ' You are','L2' : 'prompted to set','L3' : 'new goals &','L4' : 'discover new','L5' : 'desires.'}
F87={'L1' : ' You are the','L2' : 'centre of','L3' : 'attention.','L4' : '','L5' : ''}
F88={'L1' : ' You can be','L2' : 'lucky today','L3' : 'regarding your','L4' : 'creative','L5' : 'talents.'}
F89={'L1' : ' You can be','L2' : 'lucky today','L3' : 'regarding your','L4' : 'romantic','L5' : 'aspirations.'}
F90={'L1' : ' You can go','L2' : 'ahead with a','L3' : 'scheme long','L4' : 'under','L5' : 'discussion.'}
F91={'L1' : ' You can go','L2' : 'ahead with your','L3' : 'new ideas.','L4' : '','L5' : ''}
F92={'L1' : ' You can plan','L2' : 'now with','L3' : 'confidence.','L4' : '','L5' : ''}
F93={'L1' : ' You can solve','L2' : 'your problem if','L3' : 'you exert','L4' : 'yourself.','L5' : ''}
F94={'L1' : ' You deserve','L2' : 'respect and will','L3' : 'eventually get','L4' : 'it.','L5' : ''}
F95={'L1' : ' You have a','L2' : 'friendly heart','L3' : 'and will be','L4' : 'admired.','L5' : ''}
F96={'L1' : ' You have all','L2' : 'the assistance','L3' : 'and luck this','L4' : 'month to','L5' : 'succeed.'}
F97={'L1' : ' You have an','L2' : 'ambitious nature','L3' : 'and will make a','L4' : 'name for','L5' : 'yourself.'}
F98={'L1' : ' You have an','L2' : 'important new','L3' : 'venture shaping','L4' : 'up.','L5' : ''}
F99={'L1' : ' You have','L2' : 'artistic talent;','L3' : 'do something','L4' : 'creative.','L5' : ''}
F100={'L1' : ' You have found','L2' : 'good company;','L3' : 'enjoy.','L4' : '','L5' : ''}
F101={'L1' : ' You have got a','L2' : 'way with words;','L3' : 'maximize on it.','L4' : '','L5' : ''}
F102={'L1' : ' You have the','L2' : 'ability to touch','L3' : 'many people.','L4' : '','L5' : ''}
F103={'L1' : ' You shall','L2' : 'attain great','L3' : 'wisdom with the','L4' : 'passing years.','L5' : ''}
F104={'L1' : ' You shall know','L2' : 'good fortune in','L3' : 'the very near','L4' : 'future.','L5' : ''}
F105={'L1' : ' You shall soon','L2' : 'achieve','L3' : 'perfection.','L4' : '','L5' : ''}
F106={'L1' : ' You shall soon','L2' : 'be rewarded for','L3' : 'your endeavors.','L4' : '','L5' : ''}
F107={'L1' : ' You shall soon','L2' : 'gain the','L3' : 'attention of','L4' : 'those who count.','L5' : ''}
F108={'L1' : ' You shall soon','L2' : 'make a long','L3' : 'overdue personal','L4' : 'decision.','L5' : ''}
F109={'L1' : ' You were born','L2' : 'with the skill','L3' : 'to easily','L4' : 'communicate with','L5' : 'people.'}
F110={'L1' : ' You will be a','L2' : 'contest winner.','L3' : '','L4' : '','L5' : ''}
F111={'L1' : ' You will be','L2' : 'deeply loved.','L3' : '','L4' : '','L5' : ''}
F112={'L1' : ' You will be','L2' : 'delighted by an','L3' : 'unexpected gift.','L4' : '','L5' : ''}
F113={'L1' : ' You will be','L2' : 'drawn to the','L3' : 'glamour of the','L4' : 'stage.','L5' : ''}
F114={'L1' : ' You will be','L2' : 'fortunate in','L3' : 'everything you','L4' : 'put your hands','L5' : 'to.'}
F115={'L1' : ' You will be','L2' : 'happy in life.','L3' : '','L4' : '','L5' : ''}
F116={'L1' : ' You will be','L2' : 'honoured.','L3' : '','L4' : '','L5' : ''}
F117={'L1' : ' You will be in','L2' : 'the best','L3' : 'position.','L4' : '','L5' : ''}
F118={'L1' : ' You will be','L2' : 'inspired to new','L3' : 'heights of','L4' : 'accomplishment.','L5' : ''}
F119={'L1' : ' You will be','L2' : 'showered with','L3' : 'good luck.','L4' : '','L5' : ''}
F120={'L1' : ' You will be','L2' : 'socially','L3' : 'successful.','L4' : '','L5' : ''}
F121={'L1' : ' You will be','L2' : 'successful in','L3' : 'any gathering.','L4' : '','L5' : ''}
F122={'L1' : ' You will be','L2' : 'successful in','L3' : 'competitive','L4' : 'sports.','L5' : ''}
F123={'L1' : ' You will be the','L2' : 'centre of a','L3' : 'special groups','L4' : 'attention.','L5' : ''}
F124={'L1' : ' You will be the','L2' : 'guest of a','L3' : 'gracious host.','L4' : '','L5' : ''}
F125={'L1' : ' You will','L2' : 'benefit','L3' : 'immediately if','L4' : 'you co-operate','L5' : 'for now.'}
F126={'L1' : ' You will dance','L2' : 'to a different','L3' : 'beat next','L4' : 'summer.','L5' : ''}
F127={'L1' : ' You will','L2' : 'discover a new','L3' : 'area of','L4' : 'interest.','L5' : ''}
F128={'L1' : ' You will','L2' : 'discover your','L3' : 'hidden talents.','L4' : '','L5' : ''}
F129={'L1' : ' You will do','L2' : 'well when you','L3' : 'expand your','L4' : 'horizons.','L5' : ''}
F130={'L1' : ' You will find','L2' : 'excitement in','L3' : 'your working','L4' : 'life.','L5' : ''}
F131={'L1' : ' You will find','L2' : 'Monday an','L3' : 'especially','L4' : 'important day.','L5' : ''}
F132={'L1' : ' You will find','L2' : 'much fulfillment','L3' : 'with someone','L4' : 'special very','L5' : 'soon.'}
F133={'L1' : ' You will find','L2' : 'security in','L3' : 'being with a','L4' : 'loved one.','L5' : ''}
F134={'L1' : ' You will get','L2' : 'comfort from a','L3' : 'new','L4' : 'relationship.','L5' : ''}
F135={'L1' : ' You will get','L2' : 'the practical','L3' : 'help you have','L4' : 'been seeking.','L5' : ''}
F136={'L1' : ' You will give','L2' : 'some thought to','L3' : 'a different','L4' : 'lifestyle.','L5' : ''}
F137={'L1' : ' You will have a','L2' : 'close encounter','L3' : 'of a serious','L4' : 'kind.','L5' : ''}
F138={'L1' : ' You will have','L2' : 'an enjoyable','L3' : 'experience.','L4' : '','L5' : ''}
F139={'L1' : ' You will have','L2' : 'an important','L3' : 'decision to make','L4' : 'next month.','L5' : ''}
F140={'L1' : ' You will have','L2' : 'good luck and','L3' : 'overcome any','L4' : 'hardships.','L5' : ''}
F141={'L1' : ' You will have','L2' : 'many friends','L3' : 'when you need','L4' : 'them.','L5' : ''}
F142={'L1' : ' You will help','L2' : 'someone in need.','L3' : '','L4' : '','L5' : ''}
F143={'L1' : ' You will lead a','L2' : 'happy life.','L3' : '','L4' : '','L5' : ''}
F144={'L1' : ' You will live a','L2' : 'long, happy','L3' : 'life.','L4' : '','L5' : ''}
F145={'L1' : ' You will make a','L2' : 'profitable','L3' : 'investment.','L4' : '','L5' : ''}
F146={'L1' : ' You will make a','L2' : 'profitable','L3' : 'transaction next','L4' : 'month.','L5' : ''}
F147={'L1' : ' You will make','L2' : 'exciting holiday','L3' : 'plans.','L4' : '','L5' : ''}
F148={'L1' : ' You will master','L2' : 'any feeling of','L3' : 'inadequacy you','L4' : 'may be having.','L5' : ''}
F149={'L1' : ' You will need','L2' : 'good reading','L3' : 'material in','L4' : 'approximately 15','L5' : 'minutes.'}
F150={'L1' : ' You will obtain','L2' : 'your goal if you','L3' : 'maintain your','L4' : 'course.','L5' : ''}
